DEFINE CPEDBUSER = &&1
DEFINE sysDBUser = &&2
prompt CPEDBUSER = &&CPEDBUSER
prompt sysDBUser = &&sysDBUser
GRANT SELECT ON &&sysDBUser..TBLMSTAFF TO &&CPEDBUSER;
GRANT SELECT ON &&sysDBUser..TBLMGROUP TO &&CPEDBUSER;
GRANT SELECT ON &&sysDBUser..TBLMGROUPACTIONREL TO &&CPEDBUSER;
GRANT SELECT ON &&sysDBUser..TBLMACTION TO &&CPEDBUSER;
GRANT SELECT ON &&sysDBUser..TBLMSYSTEMUSERGROUPREL TO &&CPEDBUSER;