delete from TBLTWSAUDIT;

ALTER TABLE TBLTWSAUDIT modify ( RESPONSECODE VARCHAR2(50 BYTE));



 CREATE TABLE TBLSINVENTORYSUBSTATUS
   (	"INVENTORYSUBSTATUSID" NUMBER(5,0), 
	"NAME" VARCHAR2(50), 
	"SYSTEMGENERATED" CHAR(1), 
	"ALIAS" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(20)
   ) ;


Insert into TBLSINVENTORYSUBSTATUS (INVENTORYSUBSTATUSID,NAME,SYSTEMGENERATED,ALIAS,DESCRIPTION) values (1,'New','N','NEW','New');
Insert into TBLSINVENTORYSUBSTATUS (INVENTORYSUBSTATUSID,NAME,SYSTEMGENERATED,ALIAS,DESCRIPTION) values (2,'Accepted','N','ACCEPTED','Accepted');
Insert into TBLSINVENTORYSUBSTATUS (INVENTORYSUBSTATUSID,NAME,SYSTEMGENERATED,ALIAS,DESCRIPTION) values (3,'Refurnished','N','REFURNISHED','Refurnished');
Insert into TBLSINVENTORYSUBSTATUS (INVENTORYSUBSTATUSID,NAME,SYSTEMGENERATED,ALIAS,DESCRIPTION) values (4,'Stand-By','N','STAND_BY','Stand-By');
Insert into TBLSINVENTORYSUBSTATUS (INVENTORYSUBSTATUSID,NAME,SYSTEMGENERATED,ALIAS,DESCRIPTION) values (5,'Returned','N','RETURNED','Returned');

CREATE SEQUENCE  TBLSINVSUBSTATUSTRANSITION_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;   

CREATE TABLE TBLSINVSUBSTATUSTRANSITION 
   (	"SUBSTATUSTRANSITIONID" NUMBER(5,0), 
	"STATUSID" NUMBER(5,0), 
	"ALLOWEDSUBSTATUSID" NUMBER(5,0)
   ) ;


Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),2,1);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),2,2);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),2,3);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),2,4);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),3,1);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),3,4);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),4,1);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),4,3);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),4,4);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),5,1);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),5,3);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),5,4);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),6,2);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),6,4);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),6,1);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),7,1);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),7,4);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),7,5);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),8,1);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),8,2);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),8,4);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),9,1);
Insert into TBLSINVSUBSTATUSTRANSITION (SUBSTATUSTRANSITIONID,STATUSID,ALLOWEDSUBSTATUSID) values ((TBLSINVSUBSTATUSTRANSITION_SEQ.nextval),9,4);


insert into tblssysprmcustomfieldtype(customfieldtypeid,name,alias,description) values ('CFT06','BandBox','BANDBOX','BandBox for multiple select in combobox');

update tblmsystemparameter set customfieldtypeid='CFT06' where alias='THRESHOLD_COUNT';


Insert into TBLMSYSTEMPARAMETER (SYSTEMPARAMETERID,SYSTEMPARAMETERGROUPID,NAME,ALIAS,VALUE,VALUESOURCE,DESCRIPTION,ALLOWOVERRIDE,LASTMODIDATE,LASTMODIBY,ISVISIBLE,CUSTOMFIELDTYPEID,CONSTRAINTEXPRESSIONID) values (9,1,'Inventory For New Order','INVENTORY_FOR_NEW_ORDER','Available','Available,Repaired with Refurbished','Inventory For New Order','Y',sysdate,'STF0001','Y','CFT06','REG05');

update tblmsystemparameter set valuesource=(select inventorystatusid from tblsinventorystatus where alias='AVAILABLE')||':Available,'||
(select inventorystatusid from tblsinventorystatus where alias='REPAIRED')||':Repaired with Refurbished' where alias='INVENTORY_FOR_NEW_ORDER';


update tblmsystemparameter set valuesource=(select inventorystatusid from tblsinventorystatus where alias='AVAILABLE')||':Available,'||
(select inventorystatusid from tblsinventorystatus where alias='REPAIRED')||':Repaired with Refurbished' where alias='THRESHOLD_COUNT';


alter table tblsinventorystatus add (transferrable char(1));

update tblsinventorystatus set transferrable='N';

update tblsinventorystatus set transferrable='Y' where alias='AVAILABLE';
update tblsinventorystatus set transferrable='Y' where alias='FAULTY';
update tblsinventorystatus set transferrable='Y' where alias='RELEASED';
update tblsinventorystatus set transferrable='Y' where alias='REPAIRED';
update tblsinventorystatus set transferrable='Y' where alias='SCRAPPED';


Insert into TBLISYSTEMACTION (ACTIONID,PARENTACTIONID,SEQUENCENUMBER,MODULEID,NAME,ACTIONALIAS,DESCRIPTION,ISAUDITABLE,ENABLEAUDIT,ENABLENOTIFICATION,USERTYPEID,PAGEURL,ENABLEVISIBLE) values ((select max(actionid)+1 from tblisystemaction),null,8,6,'Warehouse Summary','WAREHOUSE_SUMMARY','Warehouse Summary','Y','Y','N','UTY001','/WEB-INF/pages/core/master/warehouse/warehouse-summary.zul','Y');


Insert into TBLISYSTEMACTION (ACTIONID,PARENTACTIONID,SEQUENCENUMBER,MODULEID,NAME,ACTIONALIAS,DESCRIPTION,ISAUDITABLE,ENABLEAUDIT,ENABLENOTIFICATION,USERTYPEID,PAGEURL,ENABLEVISIBLE) values ((select max(actionid)+1 from tblisystemaction),null,10,1,'Order Detail','ORDER_DETAIL','Order Detail','Y','Y','N','UTY001','/WEB-INF/pages/core/inventory/orderdetail/search-order-detail.zul','Y');


Insert into TBLISYSTEMACTION (ACTIONID,PARENTACTIONID,SEQUENCENUMBER,MODULEID,NAME,ACTIONALIAS,DESCRIPTION,ISAUDITABLE,ENABLEAUDIT,ENABLENOTIFICATION,USERTYPEID,PAGEURL,ENABLEVISIBLE) values ((select max(actionid)+1 from tblisystemaction),null,9,6,'Warehouse Hierarchy','WAREHOUSE_TREEVIEW','Warehouse Hierarchy','Y','Y','N','UTY001','/WEB-INF/pages/core/master/warehouse/tree/warehouse-treeview.zul','Y');

commit;
