

CREATE SEQUENCE  TBLTWSAUDIT_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 ;
CREATE SEQUENCE  TBLTATTRIBUTETRANS_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMATTRIBUTE_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMRESOURCE_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLSRESOURCETYPE_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMPRIMARYKEY_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMBATCH_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMBATCHSUMMARY_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMINVENTORY_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMINVALIDINVENTORY_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLTINVENTORYSTUATUSLOG_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMWAREHOUSEALERT_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLSRESOURCECATEGORY_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMITEM_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMWAREHOUSE_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLSORDERSTATUS_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMWHINVENTORYSTATUS_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLTWHINSTATUSHISTORY_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMDATATAGS_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMMESSAGETEMPLATE_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLIAUDITENTRY_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMRESOURCEATTRIBUTEREL_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLSRESOURCESUBTYPE_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMTRANSFERORDER_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLTTRANSFERORDERDETAIL_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLSINVSTATUSTRANSITION_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLTINVENTORYRESERVE_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLTINVENTORYRESERVEDETAIL_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLISYSTEMAUDIT_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLTAGENTRUNDETAIL_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLTAGENTRUNQUEUE_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  AGENTSCHEDUALPARAMVALUE_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMAGENTSCHEDULE_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLMAGENTPARAMETER_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;
CREATE SEQUENCE  TBLSWAREHOUSETYPE_SEQ   MINVALUE 1   MAXVALUE 9999999999999999999999999999   INCREMENT BY 1   START WITH 1;



--------------------------------------------------------
--  DDL for Table TBLIAUDITENTRY
--------------------------------------------------------

  CREATE TABLE TBLIAUDITENTRY
   (	"AUDITENTRYID" NUMBER(12,0), 
	"SYSTEMAUDITID" NUMBER(12,0), 
	"TABLENAME" VARCHAR2(255), 
	"FIELDNAME" VARCHAR2(255), 
	"OLDVALUE" VARCHAR2(4000), 
	"NEWVALUE" VARCHAR2(4000)
   ) ;
 

   COMMENT ON TABLE TBLIAUDITENTRY  IS 'MODULE:AUDIT == Table is used to insert audit entries with changes recently made';

--------------------------------------------------------
--  DDL for Table TBLISYSTEMACTION
--------------------------------------------------------

 CREATE TABLE TBLISYSTEMACTION
   (	"ACTIONID" NUMBER(8,0), 
	"PARENTACTIONID" NUMBER(8,0), 
	"SEQUENCENUMBER" NUMBER(3,0), 
	"MODULEID" NUMBER(5,0), 
	"NAME" VARCHAR2(100), 
	"ACTIONALIAS" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(255), 
	"ISAUDITABLE" VARCHAR2(1), 
	"ENABLEAUDIT" VARCHAR2(1), 
	"ENABLENOTIFICATION" VARCHAR2(1) DEFAULT 'N', 
	"USERTYPEID" CHAR(6), 
	"PAGEURL" VARCHAR2(255), 
	"ENABLEVISIBLE" CHAR(1)
   ) ;
   

--------------------------------------------------------
--  DDL for Table TBLISYSTEMAUDIT
--------------------------------------------------------

  CREATE TABLE TBLISYSTEMAUDIT 
   (	"SYSTEMAUDITID" NUMBER(12,0), 
	"AUDITDATE" TIMESTAMP (6), 
	"ACTIONID" NUMBER(8,0), 
	"USERID" VARCHAR2(10), 
	"REASON" VARCHAR2(4000), 
	"REMARKS" VARCHAR2(255), 
	"IPADDRESS" VARCHAR2(100), 
	"AUDITTYPEID" CHAR(5)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLISYSTEMMODULES
--------------------------------------------------------

  CREATE TABLE TBLISYSTEMMODULES
   (	"MODULEID" NUMBER(5,0), 
	"NAME" VARCHAR2(40), 
	"SEQUENCENUMBER" NUMBER(3,0), 
	"ALIAS" VARCHAR2(40), 
	"DESCRIPTION" VARCHAR2(100), 
	"PANEL" VARCHAR2(5)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMAGENT
--------------------------------------------------------

  CREATE TABLE TBLMAGENT
   (	"AGENTID" VARCHAR2(5), 
	"NAME" VARCHAR2(60), 
	"DESCRIPTION" VARCHAR2(255), 
	"IMPLCLASS" VARCHAR2(1000), 
	"EXECUTIONTYPEID" VARCHAR2(10), 
	"EXEPERIODINMIN" NUMBER(10,0), 
	"PRIORITY" NUMBER(5,0), 
	"ISPARAMETERREQUIRED" CHAR(1), 
	"COMMONSTATUSID" VARCHAR2(5), 
	"ISVISIBLE" CHAR(1), 
	"ISACTIVE" CHAR(1), 
	"CREATEDATE" TIMESTAMP (6), 
	"CREATEDBY" VARCHAR2(10), 
	"LASTMODIDATE" TIMESTAMP (6), 
	"LASTMODIBY" VARCHAR2(10), 
	"LASTEXETIME" TIMESTAMP (6), 
	"ISSCHEDULABLE" CHAR(1)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMAGENTCONFIG
--------------------------------------------------------

  CREATE TABLE TBLMAGENTCONFIG
   (	"AGENTID" VARCHAR2(5), 
	"ARMECONCURRENCYLIMIT" NUMBER(3,0), 
	"ARECONCURRENCYLIMIT" NUMBER(3,0), 
	"PARMECHUNKSIZE" NUMBER(6,0), 
	"ARMECHUNKSIZELIMIT" NUMBER(6,0), 
	"PARECHUNKSIZE" NUMBER(6,0), 
	"ARECHUNKSIZELIMIT" NUMBER(6,0), 
	"OVERRULEAMECHUNKSIZE" CHAR(1), 
	"OVERRULEAECHUNKSIZE" CHAR(1), 
	"REASON" VARCHAR2(1000)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMAGENTPARAMETER
--------------------------------------------------------

  CREATE TABLE TBLMAGENTPARAMETER
   (	"AGENTPARAMID" NUMBER(9,0), 
	"AGENTID" VARCHAR2(5), 
	"NAME" VARCHAR2(100), 
	"ALIAS" VARCHAR2(100), 
	"CUSTOMFIELDTYPEID" VARCHAR2(10), 
	"VALUESOURCE" VARCHAR2(4000), 
	"CONSTRAINTEXPRESSIONID" CHAR(5), 
	"SEQUENCENUMBER" NUMBER(6,0), 
	"DEFAULTVALUE" VARCHAR2(500), 
	"ISREADONLY" CHAR(1)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMAGENTSCHEDUALPARAMVALUE
--------------------------------------------------------

  CREATE TABLE TBLMAGENTSCHEDUALPARAMVALUE
   (	"SCHEDULEPARAMVALUEID" NUMBER(9,0), 
	"AGENTSCHEDULEID" NUMBER(9,0), 
	"PARAMETERALIAS" VARCHAR2(100), 
	"TEXTVALUE" VARCHAR2(4000), 
	"CREATEDATE" TIMESTAMP (6)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMAGENTSCHEDULE
--------------------------------------------------------

  CREATE TABLE TBLMAGENTSCHEDULE
   (	"AGENTSCHEDULEID" NUMBER(9,0), 
	"AGENTID" VARCHAR2(5), 
	"NAME" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(255), 
	"PRIORITY" NUMBER(5,0), 
	"EXECUTIONTYPEID" VARCHAR2(10), 
	"REQUIREDNUMBEROFEXECUTIONS" NUMBER(6,0), 
	"EXECUTIONSTARTDATE" TIMESTAMP (6), 
	"EXEPERIODINMIN" NUMBER(10,0), 
	"LASTEXECUTIONDATE" TIMESTAMP (6), 
	"REASONFORSCHEDULE" VARCHAR2(255), 
	"EXECUTIONSTATUSID" VARCHAR2(10), 
	"OWNEDBY" VARCHAR2(10), 
	"CREATEDATE" TIMESTAMP (6), 
	"CREATEDBY" VARCHAR2(10), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"LASTMODIFIEDBY" VARCHAR2(10), 
	"SCHEDULEPATTERN" VARCHAR2(100), 
	"STATUSID" NUMBER(6,0)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMATTRIBUTE
--------------------------------------------------------

  CREATE TABLE TBLMATTRIBUTE
   (	"ATTRIBUTEID" NUMBER(5,0), 
	"NAME" VARCHAR2(50), 
	"ATTRIBUTEREL" VARCHAR2(50), 
	"CREATEDATE" DATE, 
	"CREATEDBYSTAFFID" VARCHAR2(7), 
	"LASTMODIFIEDDATE" DATE, 
	"LASTMODIFIEDDATEBYSTAFFID" VARCHAR2(7), 
	"SYSTEMGENERATED" CHAR(1), 
	"DATATYPE" VARCHAR2(30), 
	"SOURCEVALUE" VARCHAR2(255), 
	"MANDATORY" CHAR(1), 
	"REASON" VARCHAR2(255), 
	"ISUNIQUE" CHAR(1)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMBATCH
--------------------------------------------------------

  CREATE TABLE TBLMBATCH
   (	"BATCHID" NUMBER(7,0), 
	"BATCHNUMBER" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(255), 
	"SYSTEMGENERATED" CHAR(1), 
	"CREATEDATE" DATE, 
	"CREATEDBYSTAFFID" CHAR(7), 
	"LASTMODIFIEDDATE" DATE, 
	"LASTMODIFIEDDATEBYSTAFFID" CHAR(7), 
	"VALIDCOUNT" NUMBER(7,0), 
	"INVALIDCOUNT" NUMBER(7,0)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMBATCHSUMMARY
--------------------------------------------------------

  CREATE TABLE TBLMBATCHSUMMARY
   (	"ID" NUMBER(7,0), 
	"BATCHID" NUMBER(7,0), 
	"RESOURCEID" NUMBER(5,0), 
	"NUMBERFROM" VARCHAR2(20), 
	"NUMBERTO" VARCHAR2(20), 
	"NUMBERCOUNT" NUMBER(7,0)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMCONSTRAINTEXPRESSION
--------------------------------------------------------

  CREATE TABLE TBLMCONSTRAINTEXPRESSION
   (	"CONSTRAINTEXPRESSIONID" CHAR(5), 
	"NAME" VARCHAR2(40), 
	"DESCRIPTION" VARCHAR2(255), 
	"REGEX" VARCHAR2(255)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMDATATAGS
--------------------------------------------------------

  CREATE TABLE TBLMDATATAGS
   (	"TAGID" NUMBER(5,0), 
	"TAGNAME" VARCHAR2(255), 
	"PARAM1" VARCHAR2(255), 
	"PARAM2" VARCHAR2(1000)
   ) ;
 

   COMMENT ON COLUMN TBLMDATATAGS.TAGID IS 'Store Tag Id.';
 
   COMMENT ON COLUMN TBLMDATATAGS.TAGNAME IS 'Store Tag Name Id.';
 
   COMMENT ON COLUMN TBLMDATATAGS.PARAM1 IS 'Stores the key for formatting.';
 
   COMMENT ON COLUMN TBLMDATATAGS.PARAM2 IS 'Stores the value for formatting.';
 
   COMMENT ON TABLE TBLMDATATAGS  IS 'Store Message Data Tag Information';

--------------------------------------------------------
--  DDL for Table TBLMINVALIDINVENTORY
--------------------------------------------------------

  CREATE TABLE TBLMINVALIDINVENTORY
   (	"ID" NUMBER(10,0), 
	"BATCHID" NUMBER(7,0), 
	"INVENTORYSTATUSID" NUMBER(5,0), 
	"ERRORDESC" VARCHAR2(255), 
	"WAREHOUSENAME" VARCHAR2(50), 
	"ITEMREFNAME" VARCHAR2(50)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMINVENTORY
--------------------------------------------------------

  CREATE TABLE TBLMINVENTORY 
   (	"INVENTORYID" NUMBER(12,0), 
	"BATCHID" NUMBER(7,0), 
	"STATUSID" NUMBER(5,0), 
	"WAREHOUSEID" NUMBER(5,0), 
	"RESOURCEID" NUMBER(5,0), 
	"DISTRIBUTORID" VARCHAR2(7), 
	"CREATEDATE" DATE, 
	"CREATEDBYSTAFFID" VARCHAR2(7), 
	"LASTMODIFIEDDATE" DATE, 
	"LASTMODIFIEDDATEBYSTAFFID" VARCHAR2(7), 
	"ERRORDESC" VARCHAR2(255), 
	"PARTNERREFID" VARCHAR2(20), 
	"PARTNERTYPE" VARCHAR2(30), 
	"CHANNELTYPE" VARCHAR2(30), 
	"CUTROMERREFID" VARCHAR2(20), 
	"ORDERID" VARCHAR2(10), 
	"INVENTORYNO" VARCHAR2(20), 
	"SYSTEMGENERATED" CHAR(1), 
	"EXTERNALREFERENCEID" VARCHAR2(20), 
	"ACCEPTED" CHAR(1), 
	"REFURBISHED" CHAR(1), 
	"STANDBY" CHAR(1), 
	"NEW" CHAR(1), 
	"RESERVEDDATE" DATE, 
	"TRANSFERINVENTORYSTATUS" VARCHAR2(10)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMMESSAGETEMPLATE
--------------------------------------------------------

  CREATE TABLE TBLMMESSAGETEMPLATE
   (	"TEMPLATEID" NUMBER(5,0), 
	"ACTIONID" NUMBER(5,0), 
	"TEMPLATE" VARCHAR2(4000), 
	"SUPPORTEDTAGS" VARCHAR2(4000)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMPRIMARYKEY
--------------------------------------------------------

  CREATE TABLE TBLMPRIMARYKEY
   (	"PRIMARYKEYID" NUMBER(6,0), 
	"ALIAS" VARCHAR2(80), 
	"PREFIX" VARCHAR2(80), 
	"LENGTH" NUMBER(10,0), 
	"POSTFIX" VARCHAR2(80), 
	"CURRENTVALUE" NUMBER(10,0)
   ) ;
 

   COMMENT ON TABLE TBLMPRIMARYKEY  IS 'Primarykey table is used for  application  table sequence ID';

--------------------------------------------------------
--  DDL for Table TBLMRESOURCE
--------------------------------------------------------

  CREATE TABLE TBLMRESOURCE 
   (	"RESOURCEID" NUMBER(5,0), 
	"NAME" VARCHAR2(50), 
	"MODEL" VARCHAR2(50), 
	"VENDOR" VARCHAR2(50), 
	"CREATEDATE" DATE, 
	"CREATEDBYSTAFFID" VARCHAR2(7), 
	"LASTMODIFIEDDATE" DATE, 
	"LASTMODIFIEDDATEBYSTAFFID" VARCHAR2(7), 
	"SYSTEMGENERATED" CHAR(1), 
	"EDITABLE" CHAR(1), 
	"ALIAS" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(255), 
	"REFERENCEID" VARCHAR2(50), 
	"RESOURCETYPEID" NUMBER(5,0), 
	"PREFIX" CHAR(3), 
	"REASON" VARCHAR2(255), 
	"RESOURCECATEGORYID" NUMBER(5,0), 
	"RESOURCESUBTYPEID" NUMBER(5,0), 
	"RESOURCENUMBER" VARCHAR2(20)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMRESOURCEATTRIBUTEREL
--------------------------------------------------------

  CREATE TABLE TBLMRESOURCEATTRIBUTEREL
   (	"RESOURCEATTRRELID" NUMBER(5,0), 
	"ATTRIBUTEID" NUMBER(5,0), 
	"RESOURCEID" NUMBER(5,0)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMSYSTEMPARAMETER
--------------------------------------------------------

  CREATE TABLE TBLMSYSTEMPARAMETER 
   (	"SYSTEMPARAMETERID" NUMBER(11,0), 
	"SYSTEMPARAMETERGROUPID" NUMBER(11,0), 
	"NAME" VARCHAR2(40), 
	"ALIAS" VARCHAR2(50), 
	"VALUE" VARCHAR2(100), 
	"VALUESOURCE" VARCHAR2(200), 
	"DESCRIPTION" VARCHAR2(255) DEFAULT NULL, 
	"ALLOWOVERRIDE" CHAR(1), 
	"LASTMODIDATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"LASTMODIBY" VARCHAR2(10), 
	"ISVISIBLE" CHAR(1), 
	"CUSTOMFIELDTYPEID" CHAR(5) DEFAULT 'CFT01', 
	"CONSTRAINTEXPRESSIONID" CHAR(5)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMSYSTEMPARAMETERGROUP
--------------------------------------------------------

  CREATE TABLE TBLMSYSTEMPARAMETERGROUP
   (	"SYSTEMPARAMETERGROUPID" NUMBER(11,0), 
	"NAME" VARCHAR2(40), 
	"ALIAS" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(100) DEFAULT NULL, 
	"ISVISIBLE" CHAR(1)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMTRANSFERORDER
--------------------------------------------------------

  CREATE TABLE TBLMTRANSFERORDER
   (	"TRANSFERORDERID" NUMBER(7,0), 
	"TRANSFERORDERNO" VARCHAR2(20), 
	"FROMWAREHOUSEID" NUMBER(5,0), 
	"TOWAREHOUSEID" NUMBER(5,0), 
	"CREATEDATE" DATE, 
	"CREATEDBYSTAFFID" VARCHAR2(7), 
	"LASTMODIFIEDDATE" DATE, 
	"LASTMODIFIEDDATEBYSTAFFID" VARCHAR2(7)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMWAREHOUSE
--------------------------------------------------------

  CREATE TABLE TBLMWAREHOUSE
   (	"WAREHOUSEID" NUMBER(5,0), 
	"NAME" VARCHAR2(50), 
	"ALIAS" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(255), 
	"CREATEDATE" DATE, 
	"CREATEDBYSTAFFID" VARCHAR2(7), 
	"LASTMODIFIEDDATE" DATE, 
	"LASTMODIFIEDDATEBYSTAFFID" VARCHAR2(7), 
	"SYSTEMGENERATED" CHAR(1), 
	"EDITABLE" CHAR(1), 
	"LOCATION" VARCHAR2(20), 
	"PARENTWAREHOUSEID" NUMBER(5,0), 
	"REASON" VARCHAR2(255), 
	"WAREHOUSETYPEID" NUMBER(5,0), 
	"OWNER" VARCHAR2(50), 
	"CONTACTNO" VARCHAR2(20), 
	"EMAILID" VARCHAR2(50)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMWAREHOUSEALERT
--------------------------------------------------------

  CREATE TABLE TBLMWAREHOUSEALERT
   (	"WAREHOUSTHRESHOLDID" NUMBER(5,0), 
	"WAREHOUSEID" NUMBER(5,0), 
	"RESOURCETYPEID" NUMBER(5,0), 
	"THRESHOLDVALUE" NUMBER(5,0), 
	"CREATEDATE" DATE, 
	"CREATEDBYSTAFFID" VARCHAR2(7), 
	"LASTMODIFIEDDATE" DATE, 
	"LASTMODIFIEDDATEBYSTAFFID" VARCHAR2(7), 
	"SYSTEMGENERATED" CHAR(1), 
	"RESOURCESUBTYPEID" NUMBER(5,0), 
	"THRESHOLDTYPE" VARCHAR2(10)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLMWAREHOUSEINVENTORYSTATUS
--------------------------------------------------------

  CREATE TABLE TBLMWAREHOUSEINVENTORYSTATUS
   (	"WAREHOUSEINVENTORYSTATUSID" NUMBER(7,0), 
	"WAREHOUSEID" NUMBER(5,0), 
	"RESOURCEID" NUMBER(5,0), 
	"UPLOADED" NUMBER(10,0) DEFAULT 0, 
	"NEW" NUMBER(10,0) DEFAULT 0, 
	"AVAILABLE" NUMBER(10,0) DEFAULT 0, 
	"RESERVED" NUMBER(10,0) DEFAULT 0, 
	"IN_USE" NUMBER(10,0) DEFAULT 0, 
	"DELIVERED" NUMBER(10,0) DEFAULT 0, 
	"FAULTY" NUMBER(10,0) DEFAULT 0, 
	"RELEASED" NUMBER(10,0) DEFAULT 0, 
	"REPAIRED" NUMBER(10,0) DEFAULT 0, 
	"SCRAPPED" NUMBER(10,0) DEFAULT 0, 
	"VOID" NUMBER(10,0) DEFAULT 0, 
	"UPDATEDDATE" DATE, 
	"UPDATEDBYSTAFFID" CHAR(7)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLSAUDITTYPE
--------------------------------------------------------

  CREATE TABLE TBLSAUDITTYPE
   (	"AUDITTYPEID" CHAR(5), 
	"NAME" VARCHAR2(100), 
	"ALIAS" VARCHAR2(100), 
	"ISSYSTEMGENERATED" CHAR(1)
   ) ;
 

   COMMENT ON TABLE TBLSAUDITTYPE  IS 'MODULE:AUDIT == Table is used to map audit type ID with its name and alias';

--------------------------------------------------------
--  DDL for Table TBLSENCRYPTIONTYPE
--------------------------------------------------------

  CREATE TABLE TBLSENCRYPTIONTYPE
   (	"ENCRYPTIONTYPEID" CHAR(5), 
	"NAME" VARCHAR2(40), 
	"ALIAS" VARCHAR2(40)
   ) ;
 

   COMMENT ON TABLE TBLSENCRYPTIONTYPE  IS 'MODULE : USER: Table is used to specify encryptionType for user ';

--------------------------------------------------------
--  DDL for Table TBLSEXECUTIONSTATUS
--------------------------------------------------------

  CREATE TABLE TBLSEXECUTIONSTATUS
   (	"EXECUTIONSTATUSID" VARCHAR2(10), 
	"NAME" VARCHAR2(50), 
	"ALIAS" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(255), 
	"SYSTEMGENERATED" CHAR(1)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLSEXECUTIONTYPE
--------------------------------------------------------

  CREATE TABLE TBLSEXECUTIONTYPE
   (	"EXECUTIONTYPEID" VARCHAR2(10), 
	"NAME" VARCHAR2(50), 
	"ALIAS" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(255), 
	"SYSTEMGENERATED" CHAR(1)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLSINVENTORYORDERSTATUS
--------------------------------------------------------

  CREATE TABLE TBLSINVENTORYORDERSTATUS
   (	"ORDERSTATUSID" VARCHAR2(7), 
	"NAME" VARCHAR2(50), 
	"ALIAS" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(255), 
	"SYSTEMGENERATED" CHAR(1)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLSINVENTORYSTATUS
--------------------------------------------------------

  CREATE TABLE TBLSINVENTORYSTATUS
   (	"INVENTORYSTATUSID" NUMBER(5,0), 
	"NAME" VARCHAR2(50), 
	"SYSTEMGENERATED" CHAR(1), 
	"ALIAS" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(20)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLSINVSTATUSTRANSITION
--------------------------------------------------------

  CREATE TABLE TBLSINVSTATUSTRANSITION 
   (	"STATUSTRANSITIONID" NUMBER(5,0), 
	"STATUSID" NUMBER(5,0), 
	"ALLOWEDSTATUSID" NUMBER(5,0)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLSPARAMETERTYPE
--------------------------------------------------------

  CREATE TABLE TBLSPARAMETERTYPE
   (	"PARAMETERTYPEID" VARCHAR2(5), 
	"NAME" VARCHAR2(50), 
	"ALIAS" VARCHAR2(25), 
	"DESCRIPTION" VARCHAR2(255), 
	"SYSTEMGENERATED" CHAR(1) DEFAULT 'N'
   ) ;

--------------------------------------------------------
--  DDL for Table TBLSRESOURCECATEGORY
--------------------------------------------------------

  CREATE TABLE TBLSRESOURCECATEGORY
   (	"RESOURCECATEGORYID" NUMBER(5,0), 
	"NAME" VARCHAR2(50), 
	"SYSTEMGENERATED" CHAR(1), 
	"ALIAS" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(255)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLSRESOURCESUBTYPE
--------------------------------------------------------

  CREATE TABLE TBLSRESOURCESUBTYPE
   (	"RESOURCESUBTYPEID" NUMBER(5,0), 
	"RESOURCETYPEID" NUMBER(5,0), 
	"NAME" VARCHAR2(50), 
	"SYSTEMGENERATED" CHAR(1), 
	"ALIAS" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(255), 
	"CREATEDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"CREATEDBY" VARCHAR2(7), 
	"LASTMODIFIEDBY" VARCHAR2(7)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLSRESOURCETYPE
--------------------------------------------------------

  CREATE TABLE TBLSRESOURCETYPE
   (	"RESOURCETYPEID" NUMBER(5,0), 
	"NAME" VARCHAR2(50), 
	"SYSTEMGENERATED" CHAR(1), 
	"ALIAS" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(255), 
	"CREATEDATE" TIMESTAMP (6), 
	"LASTMODIFIEDDATE" TIMESTAMP (6), 
	"CREATEDBY" VARCHAR2(7), 
	"LASTMODIFIEDBY" VARCHAR2(7)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLSSYSPRMCUSTOMFIELDTYPE
--------------------------------------------------------

  CREATE TABLE TBLSSYSPRMCUSTOMFIELDTYPE
   (	"CUSTOMFIELDTYPEID" CHAR(5), 
	"NAME" VARCHAR2(40), 
	"ALIAS" VARCHAR2(40), 
	"DESCRIPTION" VARCHAR2(255)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLSWAREHOUSETYPE
--------------------------------------------------------

  CREATE TABLE TBLSWAREHOUSETYPE
   (	"WAREHOUSETYPEID" NUMBER(5,0), 
	"NAME" VARCHAR2(50), 
	"SYSTEMGENERATED" CHAR(1), 
	"ALIAS" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(255), 
	"REASON" VARCHAR2(255), 
	"CREATEDBYSTAFFID" VARCHAR2(7), 
	"CREATEDATE" DATE, 
	"LASTMODIFIEDDATEBYSTAFFID" VARCHAR2(7), 
	"LASTMODIFIEDDATE" DATE
   ) ;

--------------------------------------------------------
--  DDL for Table TBLTAGENTRUNDETAIL
--------------------------------------------------------

  CREATE TABLE TBLTAGENTRUNDETAIL
   (	"AGENTRUNDETAILID" NUMBER(9,0), 
	"AGENTID" VARCHAR2(5), 
	"AGENTSCHEDULEID" NUMBER(9,0), 
	"EXECUTIONTYPEID" VARCHAR2(10), 
	"PRIORITY" NUMBER(5,0), 
	"EXECUTIONSTARTDATE" TIMESTAMP (6), 
	"EXECUTIONSTOPDATE" TIMESTAMP (6), 
	"TOTALMASTERENTITIEPROCESSED" NUMBER(5,0), 
	"TOTALENTITIESPROCESSED" NUMBER(8,0), 
	"TOTALSUCCESSFULENTITIES" NUMBER(8,0), 
	"PARAMETERDETAIL" VARCHAR2(2000), 
	"EXECUTIONSTATUSID" VARCHAR2(10), 
	"TOTALSUCCESSFULMASTERENTITIES" NUMBER(5,0), 
	"REMARKS" VARCHAR2(1000)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLTAGENTRUNQUEUE
--------------------------------------------------------

  CREATE TABLE TBLTAGENTRUNQUEUE
   (	"AGENTRUNQUEUEID" NUMBER(9,0), 
	"AGENTSCHEDULEID" NUMBER(9,0), 
	"EXECUTIONDUEDATETIME" TIMESTAMP (6), 
	"AGENTID" VARCHAR2(5), 
	"EXECUTIONTYPEID" VARCHAR2(10), 
	"PRIORITY" NUMBER(5,0), 
	"AGENTRUNDETAILID" NUMBER(9,0), 
	"EXECUTIONSTATUSID" VARCHAR2(10)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLTATTRIBUTETRANS
--------------------------------------------------------

  CREATE TABLE TBLTATTRIBUTETRANS
   (	"ID" NUMBER(13,0), 
	"REFERENCEID" NUMBER(12,0), 
	"ATTRIBUTEID" NUMBER(5,0), 
	"VALUE" VARCHAR2(100), 
	"TABLEREFNAME" VARCHAR2(20)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLTINVENTORYRESERVE
--------------------------------------------------------

  CREATE TABLE TBLTINVENTORYRESERVE
   (	"RESERVATIONID" NUMBER(7,0), 
	"RESERVATIONNO" VARCHAR2(20), 
	"ORDERLINEITEMID" VARCHAR2(20), 
	"TOTALRESOURCE" NUMBER(5,0), 
	"CREATEDATE" DATE, 
	"CREATEDBYSTAFFID" VARCHAR2(7), 
	"LASTMODIFIEDDATE" DATE, 
	"LASTMODIFIEDDATEBYSTAFFID" VARCHAR2(7)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLTINVENTORYRESERVEDETAIL
--------------------------------------------------------

  CREATE TABLE TBLTINVENTORYRESERVEDETAIL
   (	"ID" NUMBER(10,0), 
	"RESERVATIONID" NUMBER(7,0), 
	"INVENTORYNO" VARCHAR2(20)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLTINVENTORYSTUATUSLOG
--------------------------------------------------------

  CREATE TABLE TBLTINVENTORYSTUATUSLOG
   (	"INVENTORYSTATUSLOGID" NUMBER(20,0), 
	"OLDSTATUSID" VARCHAR2(5), 
	"NEWSTATUSID" VARCHAR2(5), 
	"OLDSTATUSNAME" VARCHAR2(50), 
	"NEWSTATUSNAME" VARCHAR2(50), 
	"STATUSCHANGEDATE" DATE, 
	"CHANGEBYSTAFFID" CHAR(7), 
	"INVENTORYID" VARCHAR2(20), 
	"REMARK" VARCHAR2(255)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLTTRANSFERORDERDETAIL
--------------------------------------------------------

  CREATE TABLE TBLTTRANSFERORDERDETAIL
   (	"ID" NUMBER(10,0), 
	"TRANSFERORDERID" NUMBER(7,0), 
	"INVENTORYNO" VARCHAR2(20), 
	"BATCHNO" VARCHAR2(20), 
	"TRANSFERSTATUS" VARCHAR2(20), 
	"REMARK" VARCHAR2(255)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLTWHINVENTORYSTATUSHISTORY
--------------------------------------------------------

  CREATE TABLE TBLTWHINVENTORYSTATUSHISTORY
   (	"ID" NUMBER(10,0), 
	"WAREHOUSEINVENTORYSTATUSID" NUMBER(7,0), 
	"FROMWAREHOUSEID" NUMBER(5,0), 
	"TOWAREHOUSEID" NUMBER(5,0), 
	"RESOURCEID" NUMBER(5,0), 
	"REMARK" VARCHAR2(512), 
	"UPDATEDDATE" DATE, 
	"UPDATEDBYSTAFFID" CHAR(7), 
	"NUMBERCOUNT" NUMBER(7,0)
   ) ;

--------------------------------------------------------
--  DDL for Table TBLTWSAUDIT
--------------------------------------------------------

  CREATE TABLE TBLTWSAUDIT
   (	"WSAUDITID" NUMBER, 
	"EVENTTYPEID" NUMBER, 
	"EVENTNAME" VARCHAR2(100), 
	"INPUTPARAM" CLOB, 
	"OUTPARAM" CLOB, 
	"EVENTPROCESSSTATUS" VARCHAR2(20), 
	"RESPONSECODE" NUMBER, 
	"RESPONSEMESSAGE" VARCHAR2(1000), 
	"PROCESSDATE" DATE
   ) ;


CREATE TABLE TBLMVERSION
   (	"CURRENTVERSIONNUMBER" VARCHAR2(20), 
	"INSTALLATIONDATE" DATE, 
	"MODULENAME" VARCHAR2(100), 
	"HOSTNAME" VARCHAR2(255)
   ) ;
 

CREATE TABLE TBLTVERSIONHISTORY
   (	"VERSIONNUMBER" VARCHAR2(20), 
	"INSTALLATIONDATE" DATE, 
	"IPADDRESS" VARCHAR2(20), 
	"MODULENAME" VARCHAR2(100), 
	"HOSTNAME" VARCHAR2(255)
   ) ;
 

   COMMENT ON COLUMN   TBLMVERSION.CURRENTVERSIONNUMBER IS 'Store Current Vaersion Number';
 
   COMMENT ON COLUMN TBLMVERSION.INSTALLATIONDATE IS 'Store Upgrade Date';
 
   COMMENT ON COLUMN TBLMVERSION.MODULENAME IS 'Store Module Name';
 
   COMMENT ON TABLE TBLMVERSION  IS 'Store version related information';

   COMMENT ON COLUMN TBLTVERSIONHISTORY.VERSIONNUMBER IS 'Store Version Number';
 
   COMMENT ON COLUMN TBLTVERSIONHISTORY.INSTALLATIONDATE IS 'Store Date of Upgrade';
 
   COMMENT ON COLUMN TBLTVERSIONHISTORY.IPADDRESS IS 'Store IP Address';
 
   COMMENT ON COLUMN TBLTVERSIONHISTORY.MODULENAME IS 'Store Module Name';
 
   COMMENT ON TABLE  TBLTVERSIONHISTORY  IS 'Store Custom Discount Bad Format Data Related Information';  
   
   
--------------------------------------------------------
--  Constraints for Table TBLMVERSION
--------------------------------------------------------

  ALTER TABLE TBLMVERSION MODIFY ("CURRENTVERSIONNUMBER" CONSTRAINT "NN_VERSION_CURRVERSIONNUMBER" NOT NULL );
  

--------------------------------------------------------
--  Constraints for Table TBLISYSTEMMODULES
--------------------------------------------------------

  ALTER TABLE TBLISYSTEMMODULES ADD CONSTRAINT "PK_TB_SYSMODULES" PRIMARY KEY ("MODULEID") ;
 
  ALTER TABLE TBLISYSTEMMODULES MODIFY ("MODULEID" NOT NULL );
 
  ALTER TABLE TBLISYSTEMMODULES MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLISYSTEMMODULES MODIFY ("SEQUENCENUMBER" NOT NULL );
 
  ALTER TABLE TBLISYSTEMMODULES MODIFY ("ALIAS" NOT NULL );
 
  ALTER TABLE TBLISYSTEMMODULES MODIFY ("DESCRIPTION" NOT NULL );
 
  ALTER TABLE TBLISYSTEMMODULES ADD CONSTRAINT "UK_TB_SYS_ALIAS" UNIQUE ("ALIAS") ;

--------------------------------------------------------
--  Constraints for Table TBLMAGENT
--------------------------------------------------------

  ALTER TABLE TBLMAGENT ADD CONSTRAINT "AGENT_PK" PRIMARY KEY ("AGENTID") ;
 
  ALTER TABLE TBLMAGENT MODIFY ("AGENTID" NOT NULL );
 
  ALTER TABLE TBLMAGENT MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLMAGENT MODIFY ("IMPLCLASS" NOT NULL );
 
  ALTER TABLE TBLMAGENT MODIFY ("EXECUTIONTYPEID" NOT NULL );
 
  ALTER TABLE TBLMAGENT MODIFY ("EXEPERIODINMIN" NOT NULL );
 
  ALTER TABLE TBLMAGENT MODIFY ("PRIORITY" NOT NULL );
 
  ALTER TABLE TBLMAGENT MODIFY ("ISVISIBLE" NOT NULL );
 
  ALTER TABLE TBLMAGENT MODIFY ("ISACTIVE" NOT NULL );
 
  ALTER TABLE TBLMAGENT MODIFY ("CREATEDBY" NOT NULL );
 
  ALTER TABLE TBLMAGENT MODIFY ("LASTMODIBY" NOT NULL );

--------------------------------------------------------
--  Constraints for Table TBLSINVENTORYSTATUS
--------------------------------------------------------

  ALTER TABLE TBLSINVENTORYSTATUS ADD CONSTRAINT "PK_INVENTORYSTATUSID" PRIMARY KEY ("INVENTORYSTATUSID") ;
 
  ALTER TABLE TBLSINVENTORYSTATUS MODIFY ("INVENTORYSTATUSID" NOT NULL );
 
  ALTER TABLE TBLSINVENTORYSTATUS MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLSINVENTORYSTATUS MODIFY ("SYSTEMGENERATED" NOT NULL );
 
  ALTER TABLE TBLSINVENTORYSTATUS MODIFY ("ALIAS" NOT NULL );

--------------------------------------------------------
--  Constraints for Table TBLMSYSTEMPARAMETERGROUP
--------------------------------------------------------

  ALTER TABLE TBLMSYSTEMPARAMETERGROUP ADD CONSTRAINT "PK_TB_SYSTEMPARAMETERGROUP" PRIMARY KEY ("SYSTEMPARAMETERGROUPID") ;
 
  ALTER TABLE TBLMSYSTEMPARAMETERGROUP MODIFY ("SYSTEMPARAMETERGROUPID" NOT NULL );
 
  ALTER TABLE TBLMSYSTEMPARAMETERGROUP MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLMSYSTEMPARAMETERGROUP MODIFY ("ALIAS" NOT NULL );
 
  ALTER TABLE TBLMSYSTEMPARAMETERGROUP MODIFY ("ISVISIBLE" NOT NULL );
 
  ALTER TABLE TBLMSYSTEMPARAMETERGROUP ADD CONSTRAINT "UK1_TB_SYSPARAMGRP_ALIAS" UNIQUE ("ALIAS") ;
 
  ALTER TABLE TBLMSYSTEMPARAMETERGROUP ADD CONSTRAINT "UK2_TB_SYSPARAMGRP_NAME" UNIQUE ("NAME") ;

--------------------------------------------------------
--  Constraints for Table TBLSRESOURCECATEGORY
--------------------------------------------------------

  ALTER TABLE TBLSRESOURCECATEGORY MODIFY ("RESOURCECATEGORYID" NOT NULL );
 
  ALTER TABLE TBLSRESOURCECATEGORY MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLSRESOURCECATEGORY MODIFY ("SYSTEMGENERATED" NOT NULL );
 
  ALTER TABLE TBLSRESOURCECATEGORY MODIFY ("ALIAS" NOT NULL );
 
  ALTER TABLE TBLSRESOURCECATEGORY ADD CONSTRAINT "TBLSRESOURCECATEGORY_PK" PRIMARY KEY ("RESOURCECATEGORYID") ;

--------------------------------------------------------
--  Constraints for Table TBLMAGENTSCHEDUALPARAMVALUE
--------------------------------------------------------

  ALTER TABLE TBLMAGENTSCHEDUALPARAMVALUE ADD PRIMARY KEY ("SCHEDULEPARAMVALUEID") ;
 
  ALTER TABLE TBLMAGENTSCHEDUALPARAMVALUE MODIFY ("PARAMETERALIAS" NOT NULL );
 
  ALTER TABLE TBLMAGENTSCHEDUALPARAMVALUE MODIFY ("TEXTVALUE" NOT NULL );

--------------------------------------------------------
--  Constraints for Table TBLMBATCH
--------------------------------------------------------

  ALTER TABLE TBLMBATCH MODIFY ("BATCHID" NOT NULL );
 
  ALTER TABLE TBLMBATCH MODIFY ("BATCHNUMBER" NOT NULL );
 
  ALTER TABLE TBLMBATCH MODIFY ("SYSTEMGENERATED" NOT NULL );
 
  ALTER TABLE TBLMBATCH MODIFY ("CREATEDATE" NOT NULL );
 
  ALTER TABLE TBLMBATCH MODIFY ("CREATEDBYSTAFFID" NOT NULL );
 
  ALTER TABLE TBLMBATCH MODIFY ("VALIDCOUNT" NOT NULL );
 
  ALTER TABLE TBLMBATCH MODIFY ("INVALIDCOUNT" NOT NULL );
 
  ALTER TABLE TBLMBATCH ADD CONSTRAINT "TBLMBATCH_PK" PRIMARY KEY ("BATCHID") ;
 
  ALTER TABLE TBLMBATCH ADD CONSTRAINT "TBLMBATCH_UK_BATCHNO" UNIQUE ("BATCHNUMBER") ;

--------------------------------------------------------
--  Constraints for Table TBLTATTRIBUTETRANS
--------------------------------------------------------

  ALTER TABLE TBLTATTRIBUTETRANS MODIFY ("ID" NOT NULL );
 
  ALTER TABLE TBLTATTRIBUTETRANS MODIFY ("REFERENCEID" NOT NULL );
 
  ALTER TABLE TBLTATTRIBUTETRANS MODIFY ("ATTRIBUTEID" NOT NULL );
 
  ALTER TABLE TBLTATTRIBUTETRANS MODIFY ("VALUE" NOT NULL );
 
  ALTER TABLE TBLTATTRIBUTETRANS ADD CONSTRAINT "TBLTATTRIBUTETRANS_PK_ID" PRIMARY KEY ("ID") ;

--------------------------------------------------------
--  Constraints for Table TBLTWSAUDIT
--------------------------------------------------------

  ALTER TABLE TBLTWSAUDIT ADD CONSTRAINT "PK_BILLINGWSAUDIT" PRIMARY KEY ("WSAUDITID") ;

--------------------------------------------------------
--  Constraints for Table TBLSPARAMETERTYPE
--------------------------------------------------------

  ALTER TABLE TBLSPARAMETERTYPE ADD CONSTRAINT "PARAMETERTYPE_PK" PRIMARY KEY ("PARAMETERTYPEID") ;
 
  ALTER TABLE TBLSPARAMETERTYPE ADD CONSTRAINT "PARAMETERTYPE_UK_ALIAS" UNIQUE ("ALIAS") ;
 
  ALTER TABLE TBLSPARAMETERTYPE ADD CONSTRAINT "PARAMETERTYPE_UK_NAME" UNIQUE ("NAME") ;
 
  ALTER TABLE TBLSPARAMETERTYPE MODIFY ("PARAMETERTYPEID" NOT NULL );
 
  ALTER TABLE TBLSPARAMETERTYPE MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLSPARAMETERTYPE MODIFY ("ALIAS" NOT NULL );
 
  ALTER TABLE TBLSPARAMETERTYPE MODIFY ("SYSTEMGENERATED" NOT NULL );

--------------------------------------------------------
--  Constraints for Table TBLMBATCHSUMMARY
--------------------------------------------------------

  ALTER TABLE TBLMBATCHSUMMARY MODIFY ("ID" NOT NULL );
 
  ALTER TABLE TBLMBATCHSUMMARY MODIFY ("BATCHID" NOT NULL );
 
  ALTER TABLE TBLMBATCHSUMMARY MODIFY ("RESOURCEID" NOT NULL );
 
  ALTER TABLE TBLMBATCHSUMMARY MODIFY ("NUMBERFROM" NOT NULL );
 
  ALTER TABLE TBLMBATCHSUMMARY MODIFY ("NUMBERTO" NOT NULL );
 
  ALTER TABLE TBLMBATCHSUMMARY MODIFY ("NUMBERCOUNT" NOT NULL );
 
  ALTER TABLE TBLMBATCHSUMMARY ADD CONSTRAINT "TBLMBATCHSUMMARY_PK" PRIMARY KEY ("ID") ;

--------------------------------------------------------
--  Constraints for Table TBLSRESOURCETYPE
--------------------------------------------------------

  ALTER TABLE TBLSRESOURCETYPE MODIFY ("RESOURCETYPEID" NOT NULL );
 
  ALTER TABLE TBLSRESOURCETYPE MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLSRESOURCETYPE MODIFY ("SYSTEMGENERATED" NOT NULL );
 
  ALTER TABLE TBLSRESOURCETYPE MODIFY ("ALIAS" NOT NULL );
 
  ALTER TABLE TBLSRESOURCETYPE MODIFY ("CREATEDATE" NOT NULL );
 
  ALTER TABLE TBLSRESOURCETYPE MODIFY ("CREATEDBY" NOT NULL );
 
  ALTER TABLE TBLSRESOURCETYPE ADD CONSTRAINT "TBLSRESOURCETYPE_PK" PRIMARY KEY ("RESOURCETYPEID") ;
 
  ALTER TABLE TBLSRESOURCETYPE ADD CONSTRAINT "TBLSRESOURCETYPE_UK_ALIAS" UNIQUE ("ALIAS") ;
 
  ALTER TABLE TBLSRESOURCETYPE ADD CONSTRAINT "TBLSRESOURCETYPE_UK_NAME" UNIQUE ("NAME") ;

--------------------------------------------------------
--  Constraints for Table TBLMAGENTPARAMETER
--------------------------------------------------------

  ALTER TABLE TBLMAGENTPARAMETER MODIFY ("AGENTID" NOT NULL );
 
  ALTER TABLE TBLMAGENTPARAMETER MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLMAGENTPARAMETER MODIFY ("ALIAS" NOT NULL );
 
  ALTER TABLE TBLMAGENTPARAMETER MODIFY ("CUSTOMFIELDTYPEID" NOT NULL );
 
  ALTER TABLE TBLMAGENTPARAMETER MODIFY ("SEQUENCENUMBER" NOT NULL );
 
  ALTER TABLE TBLMAGENTPARAMETER ADD PRIMARY KEY ("AGENTPARAMID") ;

--------------------------------------------------------
--  Constraints for Table TBLTWHINVENTORYSTATUSHISTORY
--------------------------------------------------------

  ALTER TABLE TBLTWHINVENTORYSTATUSHISTORY MODIFY ("ID" NOT NULL );
 
  ALTER TABLE TBLTWHINVENTORYSTATUSHISTORY MODIFY ("WAREHOUSEINVENTORYSTATUSID" NOT NULL );
 
  ALTER TABLE TBLTWHINVENTORYSTATUSHISTORY MODIFY ("FROMWAREHOUSEID" NOT NULL );
 
  ALTER TABLE TBLTWHINVENTORYSTATUSHISTORY MODIFY ("TOWAREHOUSEID" NOT NULL );
 
  ALTER TABLE TBLTWHINVENTORYSTATUSHISTORY MODIFY ("RESOURCEID" NOT NULL );
 
  ALTER TABLE TBLTWHINVENTORYSTATUSHISTORY MODIFY ("UPDATEDDATE" NOT NULL );
 
  ALTER TABLE TBLTWHINVENTORYSTATUSHISTORY MODIFY ("UPDATEDBYSTAFFID" NOT NULL );
 
  ALTER TABLE TBLTWHINVENTORYSTATUSHISTORY ADD CONSTRAINT "TBLTWHINVENTORYSTATUSHIST_PK" PRIMARY KEY ("ID") ;

--------------------------------------------------------
--  Constraints for Table TBLISYSTEMAUDIT
--------------------------------------------------------

  ALTER TABLE TBLISYSTEMAUDIT ADD CONSTRAINT "PKTBSYSTEMAUDIT" PRIMARY KEY ("SYSTEMAUDITID") ;
 
  ALTER TABLE TBLISYSTEMAUDIT MODIFY ("SYSTEMAUDITID" NOT NULL );
 
  ALTER TABLE TBLISYSTEMAUDIT MODIFY ("AUDITDATE" NOT NULL );
 
  ALTER TABLE TBLISYSTEMAUDIT MODIFY ("ACTIONID" NOT NULL );
 
  ALTER TABLE TBLISYSTEMAUDIT MODIFY ("USERID" NOT NULL );

--------------------------------------------------------
--  Constraints for Table TBLTAGENTRUNQUEUE
--------------------------------------------------------

  ALTER TABLE TBLTAGENTRUNQUEUE ADD PRIMARY KEY ("AGENTRUNQUEUEID") ;

--------------------------------------------------------
--  Constraints for Table TBLSRESOURCESUBTYPE
--------------------------------------------------------

  ALTER TABLE TBLSRESOURCESUBTYPE MODIFY ("RESOURCESUBTYPEID" NOT NULL );
 
  ALTER TABLE TBLSRESOURCESUBTYPE MODIFY ("RESOURCETYPEID" NOT NULL );
 
  ALTER TABLE TBLSRESOURCESUBTYPE MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLSRESOURCESUBTYPE MODIFY ("SYSTEMGENERATED" NOT NULL );
 
  ALTER TABLE TBLSRESOURCESUBTYPE MODIFY ("ALIAS" NOT NULL );
 
  ALTER TABLE TBLSRESOURCESUBTYPE MODIFY ("CREATEDATE" NOT NULL );
 
  ALTER TABLE TBLSRESOURCESUBTYPE MODIFY ("CREATEDBY" NOT NULL );
 
  ALTER TABLE TBLSRESOURCESUBTYPE ADD CONSTRAINT "TBLSRESOURCESUBTYPE_PK" PRIMARY KEY ("RESOURCESUBTYPEID") ;
 
  ALTER TABLE TBLSRESOURCESUBTYPE ADD CONSTRAINT "TBLSRESOURCESUBTYPE_UK_ALIAS" UNIQUE ("ALIAS") ;
 
  ALTER TABLE TBLSRESOURCESUBTYPE ADD CONSTRAINT "TBLSRESOURCESUBTYPE_UK_NAME" UNIQUE ("NAME") ;

--------------------------------------------------------
--  Constraints for Table TBLSSYSPRMCUSTOMFIELDTYPE
--------------------------------------------------------

  ALTER TABLE TBLSSYSPRMCUSTOMFIELDTYPE ADD CONSTRAINT "PK_TB_SYSPRMCUSTMFIELDTYP" PRIMARY KEY ("CUSTOMFIELDTYPEID") ;
 
  ALTER TABLE TBLSSYSPRMCUSTOMFIELDTYPE MODIFY ("CUSTOMFIELDTYPEID" NOT NULL );
 
  ALTER TABLE TBLSSYSPRMCUSTOMFIELDTYPE MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLSSYSPRMCUSTOMFIELDTYPE MODIFY ("ALIAS" NOT NULL );
 
  ALTER TABLE TBLSSYSPRMCUSTOMFIELDTYPE MODIFY ("DESCRIPTION" NOT NULL );

--------------------------------------------------------
--  Constraints for Table TBLMAGENTSCHEDULE
--------------------------------------------------------

  ALTER TABLE TBLMAGENTSCHEDULE ADD PRIMARY KEY ("AGENTSCHEDULEID") ;
 
  ALTER TABLE TBLMAGENTSCHEDULE MODIFY ("AGENTID" NOT NULL );
 
  ALTER TABLE TBLMAGENTSCHEDULE MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLMAGENTSCHEDULE MODIFY ("PRIORITY" NOT NULL );
 
  ALTER TABLE TBLMAGENTSCHEDULE MODIFY ("OWNEDBY" NOT NULL );
 
  ALTER TABLE TBLMAGENTSCHEDULE MODIFY ("CREATEDATE" NOT NULL );
 
  ALTER TABLE TBLMAGENTSCHEDULE MODIFY ("CREATEDBY" NOT NULL );
 
  ALTER TABLE TBLMAGENTSCHEDULE MODIFY ("LASTMODIFIEDBY" NOT NULL );
 
  ALTER TABLE TBLMAGENTSCHEDULE MODIFY ("SCHEDULEPATTERN" NOT NULL );

--------------------------------------------------------
--  Constraints for Table TBLSINVSTATUSTRANSITION
--------------------------------------------------------

  ALTER TABLE TBLSINVSTATUSTRANSITION ADD CONSTRAINT "PK_STATUSTRANSITIONID" PRIMARY KEY ("STATUSTRANSITIONID") ;
 
  ALTER TABLE TBLSINVSTATUSTRANSITION MODIFY ("STATUSTRANSITIONID" NOT NULL );
 
  ALTER TABLE TBLSINVSTATUSTRANSITION MODIFY ("STATUSID" NOT NULL );
 
  ALTER TABLE TBLSINVSTATUSTRANSITION MODIFY ("ALLOWEDSTATUSID" NOT NULL );

--------------------------------------------------------
--  Constraints for Table TBLMINVENTORY
--------------------------------------------------------

  ALTER TABLE TBLMINVENTORY ADD CONSTRAINT "PK_INVENTORYID" PRIMARY KEY ("INVENTORYID") ;
 
  ALTER TABLE TBLMINVENTORY MODIFY ("INVENTORYID" NOT NULL );
 
  ALTER TABLE TBLMINVENTORY MODIFY ("BATCHID" NOT NULL );
 
  ALTER TABLE TBLMINVENTORY MODIFY ("STATUSID" NOT NULL );
 
  ALTER TABLE TBLMINVENTORY MODIFY ("CREATEDATE" NOT NULL );
 
  ALTER TABLE TBLMINVENTORY MODIFY ("CREATEDBYSTAFFID" NOT NULL );
 
  ALTER TABLE TBLMINVENTORY MODIFY ("SYSTEMGENERATED" NOT NULL );
 
  ALTER TABLE TBLMINVENTORY MODIFY ("WAREHOUSEID" NOT NULL );
 
  ALTER TABLE TBLMINVENTORY MODIFY ("RESOURCEID" NOT NULL );
 
  ALTER TABLE TBLMINVENTORY MODIFY ("INVENTORYNO" NOT NULL );
 
  ALTER TABLE TBLMINVENTORY ADD CONSTRAINT "TBLMINVENTORY_UK_INVNO" UNIQUE ("INVENTORYNO") ;

--------------------------------------------------------
--  Constraints for Table TBLMWAREHOUSE
--------------------------------------------------------

  ALTER TABLE TBLMWAREHOUSE MODIFY ("WAREHOUSEID" NOT NULL );
 
  ALTER TABLE TBLMWAREHOUSE MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLMWAREHOUSE MODIFY ("ALIAS" NOT NULL );
  
  ALTER TABLE TBLMWAREHOUSE MODIFY ("WAREHOUSETYPEID" NOT NULL );
 
  ALTER TABLE TBLMWAREHOUSE MODIFY ("SYSTEMGENERATED" NOT NULL );
 
  ALTER TABLE TBLMWAREHOUSE MODIFY ("EDITABLE" NOT NULL );
 
  ALTER TABLE TBLMWAREHOUSE ADD CONSTRAINT "TBLMWAREHOUSE_PK" PRIMARY KEY ("WAREHOUSEID") ;
 
  ALTER TABLE TBLMWAREHOUSE ADD CONSTRAINT "TBLMWAREHOUSE_UK_ALIAS" UNIQUE ("ALIAS") ;
 
  ALTER TABLE TBLMWAREHOUSE ADD CONSTRAINT "TBLMWAREHOUSE_UK_WHNAME" UNIQUE ("NAME") ;

--------------------------------------------------------
--  Constraints for Table TBLMRESOURCEATTRIBUTEREL
--------------------------------------------------------

  ALTER TABLE TBLMRESOURCEATTRIBUTEREL ADD CONSTRAINT "PKRESOURCEATTRIBUTERELL" PRIMARY KEY ("RESOURCEATTRRELID") ;
 
  ALTER TABLE TBLMRESOURCEATTRIBUTEREL MODIFY ("RESOURCEATTRRELID" NOT NULL );
 
  ALTER TABLE TBLMRESOURCEATTRIBUTEREL MODIFY ("ATTRIBUTEID" NOT NULL );
 
  ALTER TABLE TBLMRESOURCEATTRIBUTEREL MODIFY ("RESOURCEID" NOT NULL );
 
  ALTER TABLE TBLMRESOURCEATTRIBUTEREL ADD CONSTRAINT "TBLMRESOURCEATTRIBUTEREL_UK" UNIQUE ("ATTRIBUTEID", "RESOURCEID") ;

--------------------------------------------------------
--  Constraints for Table TBLMTRANSFERORDER
--------------------------------------------------------

  ALTER TABLE TBLMTRANSFERORDER MODIFY ("TRANSFERORDERID" NOT NULL );
 
  ALTER TABLE TBLMTRANSFERORDER MODIFY ("CREATEDATE" NOT NULL );
 
  ALTER TABLE TBLMTRANSFERORDER MODIFY ("CREATEDBYSTAFFID" NOT NULL );
 
  ALTER TABLE TBLMTRANSFERORDER ADD CONSTRAINT "TBLMTRANSFERORDER_PK" PRIMARY KEY ("TRANSFERORDERID") ;

--------------------------------------------------------
--  Constraints for Table TBLMINVALIDINVENTORY
--------------------------------------------------------

  ALTER TABLE TBLMINVALIDINVENTORY MODIFY ("BATCHID" NOT NULL );
 
  ALTER TABLE TBLMINVALIDINVENTORY MODIFY ("ID" NOT NULL );
 
  ALTER TABLE TBLMINVALIDINVENTORY MODIFY ("INVENTORYSTATUSID" NOT NULL );
 
  ALTER TABLE TBLMINVALIDINVENTORY ADD CONSTRAINT "TBLMINVALIDINVENTORY_PK" PRIMARY KEY ("ID") ;

--------------------------------------------------------
--  Constraints for Table TBLTINVENTORYRESERVE
--------------------------------------------------------

  ALTER TABLE TBLTINVENTORYRESERVE MODIFY ("RESERVATIONID" NOT NULL );
 
  ALTER TABLE TBLTINVENTORYRESERVE MODIFY ("RESERVATIONNO" NOT NULL );
 
  ALTER TABLE TBLTINVENTORYRESERVE MODIFY ("TOTALRESOURCE" NOT NULL );
 
  ALTER TABLE TBLTINVENTORYRESERVE MODIFY ("CREATEDATE" NOT NULL );
 
  ALTER TABLE TBLTINVENTORYRESERVE MODIFY ("CREATEDBYSTAFFID" NOT NULL );
 
  ALTER TABLE TBLTINVENTORYRESERVE ADD CONSTRAINT "TBLTINVENTORYRESERVE_PK" PRIMARY KEY ("RESERVATIONID") ;
 
  ALTER TABLE TBLTINVENTORYRESERVE ADD CONSTRAINT "UK_RESERVATIONNO" UNIQUE ("RESERVATIONNO") ;

--------------------------------------------------------
--  Constraints for Table TBLMDATATAGS
--------------------------------------------------------

  ALTER TABLE TBLMDATATAGS ADD CONSTRAINT "NN_TAGID_DATATAGS" CHECK (TAGID
IS NOT NULL) ;
 
  ALTER TABLE TBLMDATATAGS ADD CONSTRAINT "NN_TAGNAME_DATATAGS" CHECK (TAGNAME
IS NOT NULL) ;
 
  ALTER TABLE TBLMDATATAGS ADD CONSTRAINT "PK_DATATAGS" PRIMARY KEY ("TAGID") ;
 
  ALTER TABLE TBLMDATATAGS ADD UNIQUE ("TAGNAME") ;

--------------------------------------------------------
--  Constraints for Table TBLSWAREHOUSETYPE
--------------------------------------------------------

  ALTER TABLE TBLSWAREHOUSETYPE MODIFY ("WAREHOUSETYPEID" NOT NULL );
 
  ALTER TABLE TBLSWAREHOUSETYPE MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLSWAREHOUSETYPE MODIFY ("SYSTEMGENERATED" NOT NULL );
 
  ALTER TABLE TBLSWAREHOUSETYPE MODIFY ("ALIAS" NOT NULL );
 
  ALTER TABLE TBLSWAREHOUSETYPE MODIFY ("CREATEDBYSTAFFID" NOT NULL );
 
  ALTER TABLE TBLSWAREHOUSETYPE MODIFY ("CREATEDATE" NOT NULL );
 
  ALTER TABLE TBLSWAREHOUSETYPE ADD CONSTRAINT "TBLSWAREHOUSETYPE_PK" PRIMARY KEY ("WAREHOUSETYPEID") ;
 
  ALTER TABLE TBLSWAREHOUSETYPE ADD CONSTRAINT "TBLSWAREHOUSETYPE_UK_ALIAS" UNIQUE ("ALIAS") ;

--------------------------------------------------------
--  Constraints for Table TBLMWAREHOUSEINVENTORYSTATUS
--------------------------------------------------------

  ALTER TABLE TBLMWAREHOUSEINVENTORYSTATUS MODIFY ("WAREHOUSEINVENTORYSTATUSID" NOT NULL );
 
  ALTER TABLE TBLMWAREHOUSEINVENTORYSTATUS MODIFY ("WAREHOUSEID" NOT NULL );
 
  ALTER TABLE TBLMWAREHOUSEINVENTORYSTATUS MODIFY ("RESOURCEID" NOT NULL );
 
  ALTER TABLE TBLMWAREHOUSEINVENTORYSTATUS MODIFY ("UPDATEDDATE" NOT NULL );
 
  ALTER TABLE TBLMWAREHOUSEINVENTORYSTATUS MODIFY ("UPDATEDBYSTAFFID" NOT NULL );
 
  ALTER TABLE TBLMWAREHOUSEINVENTORYSTATUS MODIFY ("NEW" NOT NULL );
 
  ALTER TABLE TBLMWAREHOUSEINVENTORYSTATUS ADD CONSTRAINT "TBLMWAREHOUSEINVENTORYSTA_PK" PRIMARY KEY ("WAREHOUSEINVENTORYSTATUSID") ;
 
  ALTER TABLE TBLMWAREHOUSEINVENTORYSTATUS ADD CONSTRAINT "UK_WHID_RSID" UNIQUE ("WAREHOUSEID", "RESOURCEID") ;

--------------------------------------------------------
--  Constraints for Table TBLMAGENTCONFIG
--------------------------------------------------------

  ALTER TABLE TBLMAGENTCONFIG ADD PRIMARY KEY ("AGENTID") ;

--------------------------------------------------------
--  Constraints for Table TBLMSYSTEMPARAMETER
--------------------------------------------------------

  ALTER TABLE TBLMSYSTEMPARAMETER ADD CONSTRAINT "PK_SYSPAR" PRIMARY KEY ("SYSTEMPARAMETERID") ;
 
  ALTER TABLE TBLMSYSTEMPARAMETER MODIFY ("SYSTEMPARAMETERID" NOT NULL );
 
  ALTER TABLE TBLMSYSTEMPARAMETER MODIFY ("SYSTEMPARAMETERGROUPID" NOT NULL );
 
  ALTER TABLE TBLMSYSTEMPARAMETER MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLMSYSTEMPARAMETER MODIFY ("ALIAS" NOT NULL );
 
  ALTER TABLE TBLMSYSTEMPARAMETER MODIFY ("ALLOWOVERRIDE" NOT NULL );
 
  ALTER TABLE TBLMSYSTEMPARAMETER MODIFY ("LASTMODIBY" NOT NULL );
 
  ALTER TABLE TBLMSYSTEMPARAMETER MODIFY ("ISVISIBLE" NOT NULL );
 
  ALTER TABLE TBLMSYSTEMPARAMETER MODIFY ("CUSTOMFIELDTYPEID" NOT NULL );
 
  ALTER TABLE TBLMSYSTEMPARAMETER MODIFY ("CONSTRAINTEXPRESSIONID" NOT NULL );
 
  ALTER TABLE TBLMSYSTEMPARAMETER ADD CONSTRAINT "UK_TB_SYSPAR_ALIAS" UNIQUE ("ALIAS") ;
 
  ALTER TABLE TBLMSYSTEMPARAMETER ADD CONSTRAINT "UK_TB_SYSPAR_NAME" UNIQUE ("NAME") ;

--------------------------------------------------------
--  Constraints for Table TBLMCONSTRAINTEXPRESSION
--------------------------------------------------------

  ALTER TABLE TBLMCONSTRAINTEXPRESSION ADD CONSTRAINT "CONSTRAINTEXPRESSION_PK" PRIMARY KEY ("CONSTRAINTEXPRESSIONID") ;
 
  ALTER TABLE TBLMCONSTRAINTEXPRESSION MODIFY ("CONSTRAINTEXPRESSIONID" NOT NULL );
 
  ALTER TABLE TBLMCONSTRAINTEXPRESSION MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLMCONSTRAINTEXPRESSION MODIFY ("DESCRIPTION" NOT NULL );
 
  ALTER TABLE TBLMCONSTRAINTEXPRESSION MODIFY ("REGEX" NOT NULL );

--------------------------------------------------------
--  Constraints for Table TBLIAUDITENTRY
--------------------------------------------------------

  ALTER TABLE TBLIAUDITENTRY ADD CONSTRAINT "PKTBAUDITENTRY" PRIMARY KEY ("AUDITENTRYID") ;
 
  ALTER TABLE TBLIAUDITENTRY MODIFY ("AUDITENTRYID" NOT NULL );
 
  ALTER TABLE TBLIAUDITENTRY MODIFY ("SYSTEMAUDITID" NOT NULL );
 
  ALTER TABLE TBLIAUDITENTRY MODIFY ("TABLENAME" NOT NULL );
 
  ALTER TABLE TBLIAUDITENTRY MODIFY ("FIELDNAME" NOT NULL );

--------------------------------------------------------
--  Constraints for Table TBLISYSTEMACTION
--------------------------------------------------------

  ALTER TABLE TBLISYSTEMACTION ADD CONSTRAINT "PK_TB_SYSACTION" PRIMARY KEY ("ACTIONID");
 
  ALTER TABLE TBLISYSTEMACTION MODIFY ("ACTIONID" NOT NULL );
 
  ALTER TABLE TBLISYSTEMACTION MODIFY ("SEQUENCENUMBER" NOT NULL );
 
  ALTER TABLE TBLISYSTEMACTION MODIFY ("MODULEID" NOT NULL );
 
  ALTER TABLE TBLISYSTEMACTION MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLISYSTEMACTION MODIFY ("ACTIONALIAS" NOT NULL );
 
  ALTER TABLE TBLISYSTEMACTION MODIFY ("DESCRIPTION" NOT NULL );
 
  ALTER TABLE TBLISYSTEMACTION MODIFY ("ISAUDITABLE" NOT NULL );
 
  ALTER TABLE TBLISYSTEMACTION MODIFY ("ENABLEAUDIT" NOT NULL );
 
  ALTER TABLE TBLISYSTEMACTION MODIFY ("ENABLENOTIFICATION" NOT NULL );
 
  ALTER TABLE TBLISYSTEMACTION ADD CONSTRAINT "UK_TB_SYSACTIONALIAS" UNIQUE ("ACTIONALIAS") ;

--------------------------------------------------------
--  Constraints for Table TBLSEXECUTIONTYPE
--------------------------------------------------------

  ALTER TABLE TBLSEXECUTIONTYPE ADD PRIMARY KEY ("EXECUTIONTYPEID") ;
 
  ALTER TABLE TBLSEXECUTIONTYPE MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLSEXECUTIONTYPE MODIFY ("ALIAS" NOT NULL );
 
  ALTER TABLE TBLSEXECUTIONTYPE ADD CONSTRAINT "TBLSEXECUTIONTYPE_UK_ALIAS" UNIQUE ("ALIAS") ;
 
  ALTER TABLE TBLSEXECUTIONTYPE ADD CONSTRAINT "TBLSEXECUTIONTYPE_UK_NAME" UNIQUE ("NAME") ;

--------------------------------------------------------
--  Constraints for Table TBLTINVENTORYSTUATUSLOG
--------------------------------------------------------

  ALTER TABLE TBLTINVENTORYSTUATUSLOG ADD CONSTRAINT "PK_INVENTORYSTATTUSID" PRIMARY KEY ("INVENTORYSTATUSLOGID") ;
 
  ALTER TABLE TBLTINVENTORYSTUATUSLOG MODIFY ("INVENTORYSTATUSLOGID" NOT NULL );
 
  ALTER TABLE TBLTINVENTORYSTUATUSLOG MODIFY ("OLDSTATUSID" NOT NULL );
 
  ALTER TABLE TBLTINVENTORYSTUATUSLOG MODIFY ("NEWSTATUSID" NOT NULL );
 
  ALTER TABLE TBLTINVENTORYSTUATUSLOG MODIFY ("CHANGEBYSTAFFID" NOT NULL );
 
  ALTER TABLE TBLTINVENTORYSTUATUSLOG MODIFY ("INVENTORYID" NOT NULL );

--------------------------------------------------------
--  Constraints for Table TBLTINVENTORYRESERVEDETAIL
--------------------------------------------------------

  ALTER TABLE TBLTINVENTORYRESERVEDETAIL MODIFY ("ID" NOT NULL );
 
  ALTER TABLE TBLTINVENTORYRESERVEDETAIL MODIFY ("RESERVATIONID" NOT NULL );
 
  ALTER TABLE TBLTINVENTORYRESERVEDETAIL MODIFY ("INVENTORYNO" NOT NULL );
 
  ALTER TABLE TBLTINVENTORYRESERVEDETAIL ADD CONSTRAINT "TBLTINVENTORYRESERVEDETAI_PK" PRIMARY KEY ("ID") ;

--------------------------------------------------------
--  Constraints for Table TBLSAUDITTYPE
--------------------------------------------------------

  ALTER TABLE TBLSAUDITTYPE ADD CONSTRAINT "PKTBAUDITTYPE" PRIMARY KEY ("AUDITTYPEID") ;
 
  ALTER TABLE TBLSAUDITTYPE MODIFY ("AUDITTYPEID" NOT NULL );
 
  ALTER TABLE TBLSAUDITTYPE MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLSAUDITTYPE MODIFY ("ALIAS" NOT NULL );
 
  ALTER TABLE TBLSAUDITTYPE MODIFY ("ISSYSTEMGENERATED" NOT NULL );
 
  ALTER TABLE TBLSAUDITTYPE ADD CONSTRAINT "TBLSAUDITTYPE_UK_NAME" UNIQUE ("NAME") ;
 
  ALTER TABLE TBLSAUDITTYPE ADD CONSTRAINT "UKTBADTALIAS" UNIQUE ("ALIAS") ;

--------------------------------------------------------
--  Constraints for Table TBLMMESSAGETEMPLATE
--------------------------------------------------------

  ALTER TABLE TBLMMESSAGETEMPLATE MODIFY ("TEMPLATEID" NOT NULL );
 
  ALTER TABLE TBLMMESSAGETEMPLATE MODIFY ("ACTIONID" NOT NULL );
 
  ALTER TABLE TBLMMESSAGETEMPLATE MODIFY ("TEMPLATE" NOT NULL );
 
  ALTER TABLE TBLMMESSAGETEMPLATE ADD CONSTRAINT "TBLMMESSAGETEMPLATE_PK" PRIMARY KEY ("TEMPLATEID") ;

--------------------------------------------------------
--  Constraints for Table TBLSEXECUTIONSTATUS
--------------------------------------------------------

  ALTER TABLE TBLSEXECUTIONSTATUS MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLSEXECUTIONSTATUS MODIFY ("ALIAS" NOT NULL );
 
  ALTER TABLE TBLSEXECUTIONSTATUS ADD PRIMARY KEY ("EXECUTIONSTATUSID") ;
 
  ALTER TABLE TBLSEXECUTIONSTATUS ADD CONSTRAINT "TBLSEXECUTIONSTATUS_UK_ALIAS" UNIQUE ("ALIAS") ;
 
  ALTER TABLE TBLSEXECUTIONSTATUS ADD CONSTRAINT "TBLSEXECUTIONSTATUS_UK_NAME" UNIQUE ("NAME") ;

--------------------------------------------------------
--  Constraints for Table TBLTAGENTRUNDETAIL
--------------------------------------------------------

  ALTER TABLE TBLTAGENTRUNDETAIL ADD PRIMARY KEY ("AGENTRUNDETAILID") ;

--------------------------------------------------------
--  Constraints for Table TBLSINVENTORYORDERSTATUS
--------------------------------------------------------

  ALTER TABLE TBLSINVENTORYORDERSTATUS MODIFY ("ORDERSTATUSID" NOT NULL );
 
  ALTER TABLE TBLSINVENTORYORDERSTATUS MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLSINVENTORYORDERSTATUS ADD CONSTRAINT "TBLSORDERSTATUS_PK" PRIMARY KEY ("ORDERSTATUSID") ;

--------------------------------------------------------
--  Constraints for Table TBLMRESOURCE
--------------------------------------------------------

  ALTER TABLE TBLMRESOURCE MODIFY ("RESOURCEID" NOT NULL );
 
  ALTER TABLE TBLMRESOURCE MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLMRESOURCE MODIFY ("ALIAS" NOT NULL );
 
  ALTER TABLE TBLMRESOURCE MODIFY ("RESOURCETYPEID" NOT NULL );
 
  ALTER TABLE TBLMRESOURCE MODIFY ("PREFIX" NOT NULL );
 
  ALTER TABLE TBLMRESOURCE MODIFY ("RESOURCECATEGORYID" NOT NULL );
 
  ALTER TABLE TBLMRESOURCE MODIFY ("RESOURCESUBTYPEID" NOT NULL );
 
  ALTER TABLE TBLMRESOURCE MODIFY ("RESOURCENUMBER" NOT NULL );
 
  ALTER TABLE TBLMRESOURCE ADD CONSTRAINT "TBLMITEM_NAME" UNIQUE ("NAME", "RESOURCETYPEID") ;
 
  ALTER TABLE TBLMRESOURCE ADD CONSTRAINT "TBLMITEM_PK" PRIMARY KEY ("RESOURCEID") ;
 
  ALTER TABLE TBLMRESOURCE ADD CONSTRAINT "UK_PREFIX" UNIQUE ("PREFIX") ;

--------------------------------------------------------
--  Constraints for Table TBLTTRANSFERORDERDETAIL
--------------------------------------------------------

  ALTER TABLE TBLTTRANSFERORDERDETAIL MODIFY ("ID" NOT NULL );
 
  ALTER TABLE TBLTTRANSFERORDERDETAIL MODIFY ("INVENTORYNO" NOT NULL );
 
  ALTER TABLE TBLTTRANSFERORDERDETAIL MODIFY ("BATCHNO" NOT NULL );
 
  ALTER TABLE TBLTTRANSFERORDERDETAIL ADD CONSTRAINT "TBLTTRANSFERORDERDETAIL_PK" PRIMARY KEY ("ID") ;

--------------------------------------------------------
--  Constraints for Table TBLMPRIMARYKEY
--------------------------------------------------------

  ALTER TABLE TBLMPRIMARYKEY ADD CONSTRAINT "PKTPKPRIMARYKEY" PRIMARY KEY ("PRIMARYKEYID") ;
 
  ALTER TABLE TBLMPRIMARYKEY MODIFY ("PRIMARYKEYID" NOT NULL );
 
  ALTER TABLE TBLMPRIMARYKEY MODIFY ("ALIAS" NOT NULL );
 
  ALTER TABLE TBLMPRIMARYKEY MODIFY ("LENGTH" NOT NULL );
 
  ALTER TABLE TBLMPRIMARYKEY MODIFY ("CURRENTVALUE" NOT NULL );
 
  ALTER TABLE TBLMPRIMARYKEY ADD CONSTRAINT "UK1TPKALIAS" UNIQUE ("ALIAS") ;

--------------------------------------------------------
--  Constraints for Table TBLMWAREHOUSEALERT
--------------------------------------------------------

  ALTER TABLE TBLMWAREHOUSEALERT MODIFY ("SYSTEMGENERATED" NOT NULL );
 
  ALTER TABLE TBLMWAREHOUSEALERT MODIFY ("THRESHOLDVALUE" NOT NULL );
 
  ALTER TABLE TBLMWAREHOUSEALERT ADD CONSTRAINT "TBLMWAREHOUSEALERT_PK" PRIMARY KEY ("WAREHOUSTHRESHOLDID") ;
 
  ALTER TABLE TBLMWAREHOUSEALERT ADD CONSTRAINT "UNIQUE_THRESHOLD_VALUE" UNIQUE ("WAREHOUSEID", "RESOURCETYPEID", "RESOURCESUBTYPEID") ;

--------------------------------------------------------
--  Constraints for Table TBLMATTRIBUTE
--------------------------------------------------------

  ALTER TABLE TBLMATTRIBUTE MODIFY ("ATTRIBUTEID" NOT NULL );
 
  ALTER TABLE TBLMATTRIBUTE MODIFY ("NAME" NOT NULL );
 
  ALTER TABLE TBLMATTRIBUTE MODIFY ("ATTRIBUTEREL" NOT NULL );
 
  ALTER TABLE TBLMATTRIBUTE MODIFY ("CREATEDATE" NOT NULL );
 
  ALTER TABLE TBLMATTRIBUTE MODIFY ("CREATEDBYSTAFFID" NOT NULL );
 
  ALTER TABLE TBLMATTRIBUTE MODIFY ("SYSTEMGENERATED" NOT NULL );
 
  ALTER TABLE TBLMATTRIBUTE MODIFY ("MANDATORY" NOT NULL );
 
  ALTER TABLE TBLMATTRIBUTE MODIFY ("DATATYPE" NOT NULL );
 
  ALTER TABLE TBLMATTRIBUTE ADD CONSTRAINT "TBLMATTRIBUTE_PK" PRIMARY KEY ("ATTRIBUTEID") ;
 
  ALTER TABLE TBLMATTRIBUTE ADD CONSTRAINT "TBLMATTRIBUTE_UK_NAMEREL" UNIQUE ("NAME", "ATTRIBUTEREL") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLIAUDITENTRY
--------------------------------------------------------

  ALTER TABLE TBLIAUDITENTRY ADD CONSTRAINT "FK1TBAUDITENTRYSYSACTIONID" FOREIGN KEY ("SYSTEMAUDITID")
	  REFERENCES TBLISYSTEMAUDIT ("SYSTEMAUDITID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLISYSTEMACTION
--------------------------------------------------------

  ALTER TABLE TBLISYSTEMACTION ADD CONSTRAINT "FK1_TB_SYSMODULEID" FOREIGN KEY ("MODULEID")
	  REFERENCES TBLISYSTEMMODULES ("MODULEID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLISYSTEMAUDIT
--------------------------------------------------------

  ALTER TABLE TBLISYSTEMAUDIT ADD CONSTRAINT "FK1TBSYSTEMAUDITACTIONID" FOREIGN KEY ("ACTIONID")
	  REFERENCES TBLISYSTEMACTION ("ACTIONID") ;
 
  ALTER TABLE TBLISYSTEMAUDIT ADD CONSTRAINT "TBLISYSTEMAUDIT_TBLSAUDIT_FK1" FOREIGN KEY ("AUDITTYPEID")
	  REFERENCES TBLSAUDITTYPE ("AUDITTYPEID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLMAGENT
--------------------------------------------------------

  ALTER TABLE TBLMAGENT ADD CONSTRAINT "AGENT_FK_EXETYPE" FOREIGN KEY ("EXECUTIONTYPEID")
	  REFERENCES TBLSEXECUTIONTYPE ("EXECUTIONTYPEID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLMAGENTPARAMETER
--------------------------------------------------------

  ALTER TABLE TBLMAGENTPARAMETER ADD CONSTRAINT "APARAM_FK_AGENT" FOREIGN KEY ("AGENTID")
	  REFERENCES "TBLMAGENT" ("AGENTID") ;
 
  ALTER TABLE TBLMAGENTPARAMETER ADD CONSTRAINT "APARAM_FK_CONSTR" FOREIGN KEY ("CONSTRAINTEXPRESSIONID")
	  REFERENCES TBLMCONSTRAINTEXPRESSION ("CONSTRAINTEXPRESSIONID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLMAGENTSCHEDUALPARAMVALUE
--------------------------------------------------------

  ALTER TABLE TBLMAGENTSCHEDUALPARAMVALUE ADD CONSTRAINT "SPARAN_FK_SCHEDULE" FOREIGN KEY ("AGENTSCHEDULEID")
	  REFERENCES TBLMAGENTSCHEDULE ("AGENTSCHEDULEID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLMAGENTSCHEDULE
--------------------------------------------------------

  ALTER TABLE TBLMAGENTSCHEDULE ADD CONSTRAINT "SCHEDULE_FK_AGENT" FOREIGN KEY ("AGENTID")
	  REFERENCES TBLMAGENT ("AGENTID") ;
 
  ALTER TABLE TBLMAGENTSCHEDULE ADD CONSTRAINT "SCHEDULE_FK_EXETYPE" FOREIGN KEY ("EXECUTIONTYPEID")
	  REFERENCES TBLSEXECUTIONTYPE ("EXECUTIONTYPEID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLMBATCHSUMMARY
--------------------------------------------------------

  ALTER TABLE TBLMBATCHSUMMARY ADD CONSTRAINT "FK_RESOURCEID" FOREIGN KEY ("RESOURCEID")
	  REFERENCES TBLMRESOURCE ("RESOURCEID") ;
 
  ALTER TABLE TBLMBATCHSUMMARY ADD CONSTRAINT "TBLMBATCHSUMMARY_TBLMBATC_FK1" FOREIGN KEY ("BATCHID")
	  REFERENCES TBLMBATCH ("BATCHID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLMINVALIDINVENTORY
--------------------------------------------------------

  ALTER TABLE TBLMINVALIDINVENTORY ADD CONSTRAINT "FK_INVENTORYSTATUSID" FOREIGN KEY ("INVENTORYSTATUSID")
	  REFERENCES TBLSINVENTORYSTATUS ("INVENTORYSTATUSID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLMINVENTORY
--------------------------------------------------------

  ALTER TABLE TBLMINVENTORY ADD CONSTRAINT "TBLMINVENTORY_FK_BATCHID" FOREIGN KEY ("BATCHID")
	  REFERENCES TBLMBATCH ("BATCHID") ;
 
  ALTER TABLE TBLMINVENTORY ADD CONSTRAINT "TBLMINVENTORY_FK_STATUSID" FOREIGN KEY ("STATUSID")
	  REFERENCES TBLSINVENTORYSTATUS ("INVENTORYSTATUSID") ;
 
  ALTER TABLE TBLMINVENTORY ADD CONSTRAINT "TBLMINVENTORY_FK_WHID" FOREIGN KEY ("WAREHOUSEID")
	  REFERENCES TBLMWAREHOUSE ("WAREHOUSEID") ;
 
  ALTER TABLE TBLMINVENTORY ADD CONSTRAINT "TBLMINVENTORY_TBLMRESOURC_FK1" FOREIGN KEY ("RESOURCEID")
	  REFERENCES TBLMRESOURCE ("RESOURCEID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLMMESSAGETEMPLATE
--------------------------------------------------------

  ALTER TABLE TBLMMESSAGETEMPLATE ADD CONSTRAINT "TBLMMESSAGETEMPLATE_TBLIS_FK1" FOREIGN KEY ("ACTIONID")
	  REFERENCES TBLISYSTEMACTION ("ACTIONID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLMRESOURCE
--------------------------------------------------------

  ALTER TABLE TBLMRESOURCE ADD CONSTRAINT "FK_RESOURCETYPE" FOREIGN KEY ("RESOURCETYPEID")
	  REFERENCES TBLSRESOURCETYPE ("RESOURCETYPEID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLMRESOURCEATTRIBUTEREL
--------------------------------------------------------

  ALTER TABLE TBLMRESOURCEATTRIBUTEREL ADD CONSTRAINT "FK1TBLMRESOURCEATTRIBUTEREL" FOREIGN KEY ("ATTRIBUTEID")
	  REFERENCES TBLMATTRIBUTE ("ATTRIBUTEID") ;
 
  ALTER TABLE TBLMRESOURCEATTRIBUTEREL ADD CONSTRAINT "FK2TBLMRESOURCEATTRIBUTEREL" FOREIGN KEY ("RESOURCEID")
	  REFERENCES TBLMRESOURCE ("RESOURCEID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLMSYSTEMPARAMETER
--------------------------------------------------------

  ALTER TABLE TBLMSYSTEMPARAMETER ADD CONSTRAINT "FK1_TB_SYSPAR_SPCFTYP" FOREIGN KEY ("CUSTOMFIELDTYPEID")
	  REFERENCES TBLSSYSPRMCUSTOMFIELDTYPE ("CUSTOMFIELDTYPEID") ;
 
  ALTER TABLE TBLMSYSTEMPARAMETER ADD CONSTRAINT "FK3_TB_SYSPAR_SPGID" FOREIGN KEY ("SYSTEMPARAMETERGROUPID")
	  REFERENCES TBLMSYSTEMPARAMETERGROUP ("SYSTEMPARAMETERGROUPID") ;
 
  ALTER TABLE TBLMSYSTEMPARAMETER ADD CONSTRAINT "FK_CONSTRAINTEXPID" FOREIGN KEY ("CONSTRAINTEXPRESSIONID")
	  REFERENCES TBLMCONSTRAINTEXPRESSION ("CONSTRAINTEXPRESSIONID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLMTRANSFERORDER
--------------------------------------------------------

  ALTER TABLE TBLMTRANSFERORDER ADD CONSTRAINT "TBLMTRANSFERORDER_TBLMWAR_FK1" FOREIGN KEY ("FROMWAREHOUSEID")
	  REFERENCES TBLMWAREHOUSE ("WAREHOUSEID") ;
 
  ALTER TABLE TBLMTRANSFERORDER ADD CONSTRAINT "TBLMTRANSFERORDER_TBLMWAR_FK2" FOREIGN KEY ("TOWAREHOUSEID")
	  REFERENCES TBLMWAREHOUSE ("WAREHOUSEID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLMWAREHOUSE
--------------------------------------------------------

  ALTER TABLE TBLMWAREHOUSE ADD CONSTRAINT "FK_PARENTWAREHOUSEID" FOREIGN KEY ("PARENTWAREHOUSEID")
	  REFERENCES TBLMWAREHOUSE ("WAREHOUSEID") ;
 
  ALTER TABLE TBLMWAREHOUSE ADD CONSTRAINT "WAREHOUSE_WHTYPEID" FOREIGN KEY ("WAREHOUSETYPEID")
	  REFERENCES TBLSWAREHOUSETYPE ("WAREHOUSETYPEID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLMWAREHOUSEALERT
--------------------------------------------------------

  ALTER TABLE TBLMWAREHOUSEALERT ADD CONSTRAINT "FK_RESOURCESUBTYPE_THRESHOLD" FOREIGN KEY ("RESOURCESUBTYPEID")
	  REFERENCES TBLSRESOURCESUBTYPE ("RESOURCESUBTYPEID") ;
 
  ALTER TABLE TBLMWAREHOUSEALERT ADD CONSTRAINT "FK_RESOURCETYPE_THRESHOLD" FOREIGN KEY ("RESOURCETYPEID")
	  REFERENCES TBLSRESOURCETYPE ("RESOURCETYPEID") ;
 
  ALTER TABLE TBLMWAREHOUSEALERT ADD CONSTRAINT "FK_WAREHOUSEID" FOREIGN KEY ("WAREHOUSEID")
	  REFERENCES TBLMWAREHOUSE ("WAREHOUSEID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLMWAREHOUSEINVENTORYSTATUS
--------------------------------------------------------

  ALTER TABLE TBLMWAREHOUSEINVENTORYSTATUS ADD CONSTRAINT "WH_IN_FK_RESOURCEID" FOREIGN KEY ("RESOURCEID")
	  REFERENCES TBLMRESOURCE ("RESOURCEID") ;
 
  ALTER TABLE TBLMWAREHOUSEINVENTORYSTATUS ADD CONSTRAINT "WH_IN_FK_WAREHOUSEID" FOREIGN KEY ("WAREHOUSEID")
	  REFERENCES TBLMWAREHOUSE ("WAREHOUSEID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLSINVSTATUSTRANSITION
--------------------------------------------------------

  ALTER TABLE TBLSINVSTATUSTRANSITION ADD CONSTRAINT "TBLSINVSTATUSTRANSITION_T_FK1" FOREIGN KEY ("STATUSID")
	  REFERENCES TBLSINVENTORYSTATUS ("INVENTORYSTATUSID") ;
 
  ALTER TABLE TBLSINVSTATUSTRANSITION ADD CONSTRAINT "TBLSINVSTATUSTRANSITION_T_FK2" FOREIGN KEY ("ALLOWEDSTATUSID")
	  REFERENCES TBLSINVENTORYSTATUS ("INVENTORYSTATUSID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLTAGENTRUNDETAIL
--------------------------------------------------------

  ALTER TABLE TBLTAGENTRUNDETAIL ADD CONSTRAINT "ARUNDETAIL_FK_AGENT" FOREIGN KEY ("AGENTID")
	  REFERENCES TBLMAGENT ("AGENTID") ;
 
  ALTER TABLE TBLTAGENTRUNDETAIL ADD CONSTRAINT "ARUNDETAIL_FK_SCHEDUALE" FOREIGN KEY ("AGENTSCHEDULEID")
	  REFERENCES TBLMAGENTSCHEDULE ("AGENTSCHEDULEID") ;
 
  ALTER TABLE TBLTAGENTRUNDETAIL ADD CONSTRAINT "TBLTAGENTRUNDETAIL_TBLSEX_FK1" FOREIGN KEY ("EXECUTIONSTATUSID")
	  REFERENCES TBLSEXECUTIONSTATUS ("EXECUTIONSTATUSID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLTAGENTRUNQUEUE
--------------------------------------------------------

  ALTER TABLE TBLTAGENTRUNQUEUE ADD CONSTRAINT "TBLTAGENTRUNQUEUE_TBLMAGE_FK1" FOREIGN KEY ("AGENTSCHEDULEID")
	  REFERENCES TBLMAGENTSCHEDULE ("AGENTSCHEDULEID") ;
 
  ALTER TABLE TBLTAGENTRUNQUEUE ADD CONSTRAINT "TBLTAGENTRUNQUEUE_TBLMAGE_FK2" FOREIGN KEY ("AGENTID")
	  REFERENCES TBLMAGENT ("AGENTID") ;
 
  ALTER TABLE TBLTAGENTRUNQUEUE ADD CONSTRAINT "TBLTAGENTRUNQUEUE_TBLSEXE_FK1" FOREIGN KEY ("EXECUTIONTYPEID")
	  REFERENCES TBLSEXECUTIONTYPE ("EXECUTIONTYPEID") ;
 
  ALTER TABLE TBLTAGENTRUNQUEUE ADD CONSTRAINT "TBLTAGENTRUNQUEUE_TBLSEXE_FK2" FOREIGN KEY ("EXECUTIONSTATUSID")
	  REFERENCES TBLSEXECUTIONSTATUS ("EXECUTIONSTATUSID") ;
 
  ALTER TABLE TBLTAGENTRUNQUEUE ADD CONSTRAINT "TBLTAGENTRUNQUEUE_TBLTAGE_FK1" FOREIGN KEY ("AGENTRUNDETAILID")
	  REFERENCES TBLTAGENTRUNDETAIL ("AGENTRUNDETAILID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLTATTRIBUTETRANS
--------------------------------------------------------

  ALTER TABLE TBLTATTRIBUTETRANS ADD CONSTRAINT "FK_ATTRIBUTEID" FOREIGN KEY ("ATTRIBUTEID")
	  REFERENCES TBLMATTRIBUTE ("ATTRIBUTEID") ;

--------------------------------------------------------
--  Ref Constraints for Table TBLTINVENTORYRESERVEDETAIL
--------------------------------------------------------

  ALTER TABLE TBLTINVENTORYRESERVEDETAIL ADD CONSTRAINT "TBLTINVENTORYRESERVEDETAI_FK1" FOREIGN KEY ("RESERVATIONID")
	  REFERENCES TBLTINVENTORYRESERVE ("RESERVATIONID") ;

	  commit;

