set define on;
set echo on;

DEFINE partnerDBUser="&&partner_db_user"
DEFINE partnerDBPassword="&&partner_db_password"


UPDATE TBLMWAREHOUSE SET WAREHOUSECODE=UPPER(REPLACE(NAME,' ','_')) where WAREHOUSECODE IS NULL;

ALTER table  TBLMWAREHOUSE  add CONSTRAINT TBLMWAREHOUSE_UK_WHCODE unique (WAREHOUSECODE) ;


UPDATE  TBLMMESSAGETEMPLATE SET TEMPLATE='User Warehouse Mapping Updated for Username :${name} ' where ACTIONID=(select ACTIONID from TBLISYSTEMACTION where ACTIONALIAS='USER_WAREHOUSE_MAPPING') ;


alter table  TBLMSYSTEMPARAMETER modify(VALUE VARCHAR2(150 BYTE));

 UPDATE TBLMDOCUMENTCATEGORY SET ENABLESMS='Y';

INSERT INTO TBLMSYSTEMPARAMETERGROUP (SYSTEMPARAMETERGROUPID,NAME,ALIAS,DESCRIPTION,ISVISIBLE) VALUES ((SELECT MAX(SYSTEMPARAMETERGROUPID)+1 FROM TBLMSYSTEMPARAMETERGROUP),'Notification','NOTIFICATION','Notification System Parameter','Y');
INSERT INTO TBLMCONSTRAINTEXPRESSION (CONSTRAINTEXPRESSIONID,NAME,DESCRIPTION,REGEX) VALUES ('REG10','Mobile  number',' number including + sign are valid','^\+*[0-9][0-9]{12}$');

  Insert into TBLSSYSPRMCUSTOMFIELDTYPE (CUSTOMFIELDTYPEID,NAME,ALIAS,DESCRIPTION) values ('CFT07','password','PASSWORD','Password field for password inputs');

INSERT INTO TBLMSYSTEMPARAMETER (SYSTEMPARAMETERID,SYSTEMPARAMETERGROUPID,NAME,ALIAS,VALUE,VALUESOURCE,DESCRIPTION,ALLOWOVERRIDE,LASTMODIDATE,LASTMODIBY,ISVISIBLE,CUSTOMFIELDTYPEID,CONSTRAINTEXPRESSIONID) VALUES ((SELECT MAX(SYSTEMPARAMETERID)+1 FROM TBLMSYSTEMPARAMETER),2,'Enable SMS Notification','ENABLE_SMS_NOTIFICATION','No','Yes,No','enable or disable  SMS-Notification','Y',TO_TIMESTAMP('27-SEP-14 11.28.36.850509000 AM','DD-MON-RR HH.MI.SS.FF AM'),'STF0001','Y','CFT02','REG05');
INSERT INTO TBLMSYSTEMPARAMETER (SYSTEMPARAMETERID,SYSTEMPARAMETERGROUPID,NAME,ALIAS,VALUE,VALUESOURCE,DESCRIPTION,ALLOWOVERRIDE,LASTMODIDATE,LASTMODIBY,ISVISIBLE,CUSTOMFIELDTYPEID,CONSTRAINTEXPRESSIONID) VALUES ((SELECT MAX(SYSTEMPARAMETERID)+1 FROM TBLMSYSTEMPARAMETER),2,'Enable Email Notification','ENABLE_EMAIL_NOTIFICATION','No','Yes,No','enable or disable  Email-Notification','Y',TO_TIMESTAMP('27-SEP-14 11.28.36.850509000 AM','DD-MON-RR HH.MI.SS.FF AM'),'STF0001','Y','CFT02','REG05');

  
INSERT
INTO TBLMSYSTEMPARAMETER
  (
    SYSTEMPARAMETERID,
    SYSTEMPARAMETERGROUPID,
    NAME,
    ALIAS,
    VALUE,
    VALUESOURCE,
    DESCRIPTION,
    ALLOWOVERRIDE,
    LASTMODIDATE,
    LASTMODIBY,
    ISVISIBLE,
    CUSTOMFIELDTYPEID,
    CONSTRAINTEXPRESSIONID
  )
  VALUES
  (
    (SELECT MAX(SYSTEMPARAMETERID)+1 FROM TBLMSYSTEMPARAMETER),
    1,
    'Mobile No for Resource SMS-Notification',
    'MOBILE_NO_FOR_RESOURCE_SMS_NOTIFICATION',
   '23045456564',
    NULL,
    'MOBILE Number for sending SMS-Notification for Resource',
    'Y',
    TO_TIMESTAMP('25-MAR-15 04.10.50.000000000 PM','DD-MON-RR HH.MI.SS.FF AM'),
    'STF0001',
    'Y',
    'CFT01',
    'REG10'
  );

  

  
  INSERT
INTO TBLMSYSTEMPARAMETER
  (
    SYSTEMPARAMETERID,
    SYSTEMPARAMETERGROUPID,
    NAME,
    ALIAS,
    VALUE,
    VALUESOURCE,
    DESCRIPTION,
    ALLOWOVERRIDE,
    LASTMODIDATE,
    LASTMODIBY,
    ISVISIBLE,
    CUSTOMFIELDTYPEID,
    CONSTRAINTEXPRESSIONID
  )
  VALUES
  (
    (SELECT MAX(SYSTEMPARAMETERID)+1 FROM TBLMSYSTEMPARAMETER
    )
    ,
    2,
    'SMTP Host IP Address',
    'SMTP_HOST_IP_ADDRESS',
    '192.168.0.252',
    null,
    'SMTP Host IP Address for sending Email-Notification',
    'Y',
    TO_TIMESTAMP('25-MAR-15 04.10.50.000000000 PM','DD-MON-RR HH.MI.SS.FF AM'),
    'STF0001',
    'Y',
    'CFT01',
    'REG05'
  );
INSERT INTO TBLMSYSTEMPARAMETER (SYSTEMPARAMETERID,SYSTEMPARAMETERGROUPID,NAME,ALIAS,VALUE,VALUESOURCE,DESCRIPTION,ALLOWOVERRIDE,LASTMODIDATE,LASTMODIBY,ISVISIBLE,CUSTOMFIELDTYPEID,CONSTRAINTEXPRESSIONID) VALUES((SELECT MAX(SYSTEMPARAMETERID)+1 FROM TBLMSYSTEMPARAMETER),2,'SMTP Port','SMTP_PORT','25', NULL,'SMTP Port for sending Notification','Y', TO_TIMESTAMP('25-MAR-15 04.10.50.000000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'STF0001','Y','CFT01','REG05');
INSERT INTO TBLMSYSTEMPARAMETER (SYSTEMPARAMETERID,SYSTEMPARAMETERGROUPID,NAME,ALIAS,VALUE,VALUESOURCE,DESCRIPTION,ALLOWOVERRIDE,LASTMODIDATE,LASTMODIBY,ISVISIBLE,CUSTOMFIELDTYPEID,CONSTRAINTEXPRESSIONID) VALUES((SELECT MAX(SYSTEMPARAMETERID)+1 FROM TBLMSYSTEMPARAMETER),2,'Administrator EmailId','ADMINISTRATOR_EMAILID','mtone@ec.com', NULL,'admin emailId for sending Email-Notification','Y', TO_TIMESTAMP('25-MAR-15 04.10.50.000000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'STF0001','Y','CFT01','REG03');
INSERT INTO TBLMSYSTEMPARAMETER (SYSTEMPARAMETERID,SYSTEMPARAMETERGROUPID,NAME,ALIAS,VALUE,VALUESOURCE,DESCRIPTION,ALLOWOVERRIDE,LASTMODIDATE,LASTMODIBY,ISVISIBLE,CUSTOMFIELDTYPEID,CONSTRAINTEXPRESSIONID) VALUES((SELECT MAX(SYSTEMPARAMETERID)+1 FROM TBLMSYSTEMPARAMETER),2,'Administrator Password','ADMINISTRATOR_PASSWORD','mT0N', NULL,'admin password for sending Email-Notification','Y', TO_TIMESTAMP('25-MAR-15 04.10.50.000000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'STF0001','Y','CFT07','REG05');
INSERT INTO TBLMSYSTEMPARAMETER (SYSTEMPARAMETERID,SYSTEMPARAMETERGROUPID,NAME,ALIAS,VALUE,VALUESOURCE,DESCRIPTION,ALLOWOVERRIDE,LASTMODIDATE,LASTMODIBY,ISVISIBLE,CUSTOMFIELDTYPEID,CONSTRAINTEXPRESSIONID) VALUES((SELECT MAX(SYSTEMPARAMETERID)+1 FROM TBLMSYSTEMPARAMETER),2,'SMS URL','SMS_URL','http://10.3.1.40/cgi-bin/rapidrequesthandler?uname=billing'||'&'||'passwd=billing'||'&'||'flash=false'||'&'||'concatenated=false'||'&'||'urname=8815', NULL,'SMS URL for sending Email-Notification','Y', TO_TIMESTAMP('25-MAR-15 04.10.50.000000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'STF0001','Y','CFT01','REG05');


UPDATE TBLMSYSTEMPARAMETER set SYSTEMPARAMETERGROUPID='2'  where ALIAS in('EMAIL_ALIAS_RESOURCE_TO','EMAIL_ALIAS_RESOURCE_CC');

commit;


