
CREATE VIEW VW_USER
AS
SELECT STAFFID, TO_NUMBER(SUBSTR(STAFFID,4,LENGTH(STAFFID))) STAFFID_NUM,NAME, USERNAME, PASSWORD, ENCRYPTIONTYPEID, EMAILADDRESS, PHONE, LASTLOGINTIME, MOBILE, SYSTEMUSERID
FROM TBLMSTAFF WHERE STAFFID NOT IN ('STFAGN1','STFDIS1','STFRES1');

---- ACL-ACTIONREL
CREATE VIEW VW_ACL_ACTION_REL
AS
SELECT GREL.GROUPID AS ACLGROUPID,ACTION.ALIAS AS ACTIONALIAS FROM TBLMGROUPACTIONREL GREL
INNER JOIN TBLMACTION ACTION 
ON GREL.ACTIONID=ACTION.ACTIONID ORDER BY GREL.GROUPID;

----- USER-ACL REL
CREATE VIEW VW_USER_ACL_REL
AS
SELECT STAFF.STAFFID AS USERID,USERGRPREL.GROUPID AS ACLGROUPID FROM TBLMSTAFF STAFF INNER JOIN TBLMSYSTEMUSERGROUPREL USERGRPREL
ON STAFF.SYSTEMUSERID=USERGRPREL.SYSTEMUSERID ORDER BY USERGRPREL.GROUPID;

commit;
